


--
-- Name: astellar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE astellar (
    obsid bigint,
    uid character varying(32),
    gp_id bigint,
    designation character varying(19),
    obsdate date,
    lmjd integer,
    mjd integer,
    planid character varying(40),
    spid integer,
    fiberid integer,
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    snru numeric(6,2),
    snrg numeric(6,2),
    snrr numeric(6,2),
    snri numeric(6,2),
    snrz numeric(6,2),
    class character varying(20),
    subclass character varying(20),
    z numeric(21,10),
    z_err numeric(21,10),
    ps_id bigint,
    mag_ps_g numeric(16,10),
    mag_ps_r numeric(16,10),
    mag_ps_i numeric(16,10),
    mag_ps_z numeric(16,10),
    mag_ps_y numeric(16,10),
    gaia_source_id character varying(25),
    gaia_g_mean_mag numeric(13,8),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    kp12 numeric(8,2),
    kp18 numeric(8,2),
    kp6 numeric(8,2),
    hdelta12 numeric(8,2),
    hdelta24 numeric(8,2),
    hdelta48 numeric(8,2),
    hdelta64 numeric(8,2),
    hgamma12 numeric(8,2),
    hgamma24 numeric(8,2),
    hgamma48 numeric(8,2),
    hgamma54 numeric(8,2),
    hbeta12 numeric(8,2),
    hbeta24 numeric(8,2),
    hbeta48 numeric(8,2),
    hbeta60 numeric(8,2),
    halpha12 numeric(8,2),
    halpha24 numeric(8,2),
    halpha48 numeric(8,2),
    halpha70 numeric(8,2),
    paschen13 numeric(8,2),
    paschen142 numeric(8,2),
    paschen242 numeric(8,2),
    halpha_d02 numeric(8,2),
    hbeta_d02 numeric(8,2),
    hgamma_d02 numeric(8,2),
    hdelta_d02 numeric(8,2)
);

--
-- Name: catalogue; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE catalogue (
    obsid bigint,
    uid character varying(32),
    gp_id bigint,
    designation character varying(19),
    obsdate date,
    lmjd integer,
    mjd integer,
    planid character varying(40),
    spid integer,
    fiberid integer,
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    snru numeric(6,2),
    snrg numeric(6,2),
    snrr numeric(6,2),
    snri numeric(6,2),
    snrz numeric(6,2),
    class character varying(20),
    subclass character varying(20),
    z numeric(21,10),
    z_err numeric(21,10),
    ps_id bigint,
    mag_ps_g numeric(16,10),
    mag_ps_r numeric(16,10),
    mag_ps_i numeric(16,10),
    mag_ps_z numeric(16,10),
    mag_ps_y numeric(16,10),
    gaia_source_id character varying(25),
    gaia_g_mean_mag numeric(13,8),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    fibermask integer,
    with_norm_flux smallint
);

--
-- Name: cv; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE cv (
    obsid bigint,
    uid character varying(32),
    gp_id bigint,
    designation character varying(19),
    obsdate date,
    lmjd integer,
    mjd integer,
    planid character varying(40),
    spid integer,
    fiberid integer,
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    snru numeric(6,2),
    snrg numeric(6,2),
    snrr numeric(6,2),
    snri numeric(6,2),
    snrz numeric(6,2),
    class character varying(20),
    subclass character varying(20),
    z numeric(21,10),
    z_err numeric(21,10),
    ps_id bigint,
    mag_ps_g numeric(16,10),
    mag_ps_r numeric(16,10),
    mag_ps_i numeric(16,10),
    mag_ps_z numeric(16,10),
    mag_ps_y numeric(16,10),
    gaia_source_id character varying(25),
    gaia_g_mean_mag numeric(13,8),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    class_liter character varying(20),
    period_liter numeric(16,10)
);

--
-- Name: galaxy; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE galaxy (
    obsid bigint,
    uid character varying(32),
    gp_id bigint,
    designation character varying(19),
    obsdate date,
    lmjd integer,
    mjd integer,
    planid character varying(40),
    spid integer,
    fiberid integer,
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    snru numeric(6,2),
    snrg numeric(6,2),
    snrr numeric(6,2),
    snri numeric(6,2),
    snrz numeric(6,2),
    class character varying(20),
    subclass character varying(20),
    z numeric(21,10),
    z_err numeric(21,10),
    ps_id bigint,
    mag_ps_g numeric(16,10),
    mag_ps_r numeric(16,10),
    mag_ps_i numeric(16,10),
    mag_ps_z numeric(16,10),
    mag_ps_y numeric(16,10),
    gaia_source_id character varying(25),
    gaia_g_mean_mag numeric(13,8),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    hbeta_flux numeric(16,10),
    hbeta_ew numeric(16,10),
    oiii_4960_flux numeric(16,10),
    oiii_4960_ew numeric(16,10),
    oiii_5008_flux numeric(16,10),
    oiii_5008_ew numeric(16,10),
    nii_6550_flux numeric(16,10),
    nii_6550_ew numeric(16,10),
    halpha_flux numeric(16,10),
    halpha_ew numeric(16,10),
    nii_6585_flux numeric(16,10),
    nii_6585_ew numeric(16,10),
    sii_6718_flux numeric(16,10),
    sii_6718_ew numeric(16,10),
    sii_6733_flux numeric(16,10),
    sii_6733_ew numeric(16,10),
    age_lw numeric(21,16),
    age_mw numeric(21,16),
    metal_lw numeric(21,16),
    metal_mw numeric(21,16),
    vsig numeric(21,10),
    vsig_err numeric(21,10)
);

--
-- Name: inputcatalog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE inputcatalog (
    obsid bigint,
    obsdate date,
    planid character varying(40),
    spid integer,
    fiberid integer,
    unitid character varying(16),
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    objtype character varying(16),
    magtype character varying(25),
    mag1 numeric(6,2),
    mag2 numeric(6,2),
    mag3 numeric(6,2),
    mag4 numeric(6,2),
    mag5 numeric(6,2),
    mag6 numeric(6,2),
    mag7 numeric(6,2),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    epoch character varying(7),
    tname character varying(25)
);

--
-- Name: mec; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE mec (
    uid character varying(32),
    ura numeric(16,10),
    udec numeric(16,10),
    gp_id bigint,
    obs_number integer,
    obsid_list character varying(400),
    midmjm_list character varying(400),
    z_list character varying(700),
    teff_list character varying(500),
    logg_list character varying(500),
    feh_list character varying(500),
    rv_list character varying(500),
    gaia_vari_type_sos character varying(100)
);

--
-- Name: med_catalogue; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE med_catalogue (
    mobsid character varying(20),
    obsid bigint,
    uid character varying(32),
    gp_id bigint,
    designation character varying(19),
    obsdate date,
    lmjd integer,
    mjd integer,
    planid character varying(40),
    spid integer,
    fiberid integer,
    lmjm bigint,
    band character varying(2),
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    snr numeric(6,2),
    gaia_source_id character varying(25),
    gaia_g_mean_mag numeric(13,8),
    gaia_bp_mean_mag numeric(16,10),
    gaia_rp_mean_mag numeric(16,10),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    rv_b0 numeric(10,2),
    rv_b0_err numeric(10,2),
    rv_b1 numeric(10,2),
    rv_b1_err numeric(10,2),
    rv_b_flag smallint,
    rv_r0 numeric(10,2),
    rv_r0_err numeric(10,2),
    rv_r1 numeric(10,2),
    rv_r1_err numeric(10,2),
    rv_r_flag smallint,
    rv_br0 numeric(10,2),
    rv_br0_err numeric(10,2),
    rv_br1 numeric(10,2),
    rv_br1_err numeric(10,2),
    rv_br_flag smallint,
    rv_lasp0 numeric(10,2),
    rv_lasp0_err numeric(10,2),
    rv_lasp1 numeric(10,2),
    rv_lasp1_err numeric(10,2),
    coadd smallint,
    fibermask integer,
    bad_b smallint,
    bad_r smallint,
    moon_angle numeric(5,1),
    lunardate smallint,
    moon_flg character varying(10)
);

--
-- Name: med_inputcatalog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE med_inputcatalog (
    obsid bigint,
    obsdate date,
    planid character varying(40),
    spid integer,
    fiberid integer,
    unitid character varying(16),
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    objtype character varying(16),
    magtype character varying(25),
    mag1 numeric(6,2),
    mag2 numeric(6,2),
    mag3 numeric(6,2),
    mag4 numeric(6,2),
    mag5 numeric(6,2),
    mag6 numeric(6,2),
    mag7 numeric(6,2),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    epoch character varying(7),
    tname character varying(25)
);

--
-- Name: med_mec; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE med_mec (
    uid character varying(32),
    ura numeric(16,10),
    udec numeric(16,10),
    gp_id bigint,
    obs_number integer,
    obsid_list character varying(400),
    teff_lasp_list character varying(500),
    logg_lasp_list character varying(500),
    feh_lasp_list character varying(500),
    exp_number integer,
    lmjm_list character varying(1200),
    rv_b0_list character varying(1200),
    rv_b1_list character varying(1200),
    rv_r0_list character varying(1200),
    rv_r1_list character varying(1200),
    rv_br0_list character varying(1200),
    rv_br1_list character varying(1200),
    gaia_vari_type_sos character varying(100)
);


--
-- Name: med_plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE med_plan (
    pid integer,
    obsdate date,
    planid character varying(40),
    ra numeric(11,7),
    dec numeric(11,7),
    mag numeric(5,2),
    seeing numeric(5,2),
    exptime character varying(120),
    lmjm_list character varying(1200)
);

--
-- Name: med_stellar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE med_stellar (
    mobsid character varying(20),
    obsid bigint,
    uid character varying(32),
    gp_id bigint,
    designation character varying(19),
    obsdate date,
    lmjd integer,
    mjd integer,
    planid character varying(40),
    spid integer,
    fiberid integer,
    lmjm bigint,
    band character varying(2),
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    snr numeric(6,2),
    gaia_source_id character varying(25),
    gaia_g_mean_mag numeric(13,8),
    gaia_bp_mean_mag numeric(16,10),
    gaia_rp_mean_mag numeric(16,10),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    teff_lasp numeric(10,2),
    teff_lasp_err numeric(8,2),
    logg_lasp numeric(10,3),
    logg_lasp_err numeric(8,3),
    feh_lasp numeric(10,3),
    feh_lasp_err numeric(8,3),
    vsini_lasp numeric(10,3),
    vsini_lasp_err numeric(9,3),
    rv_b0 numeric(10,2),
    rv_b0_err numeric(10,2),
    rv_b1 numeric(10,2),
    rv_b1_err numeric(10,2),
    rv_b_flag smallint,
    rv_r0 numeric(10,2),
    rv_r0_err numeric(10,2),
    rv_r1 numeric(10,2),
    rv_r1_err numeric(10,2),
    rv_r_flag smallint,
    rv_br0 numeric(10,2),
    rv_br0_err numeric(10,2),
    rv_br1 numeric(10,2),
    rv_br1_err numeric(10,2),
    rv_br_flag smallint,
    rv_lasp0 numeric(10,2),
    rv_lasp0_err numeric(10,2),
    rv_lasp1 numeric(10,2),
    rv_lasp1_err numeric(10,2),
    coadd smallint,
    fibermask integer,
    alpha_m_cnn numeric(10,3),
    teff_cnn numeric(10,2),
    logg_cnn numeric(10,3),
    feh_cnn numeric(10,3),
    c_fe numeric(10,6),
    n_fe numeric(10,6),
    o_fe numeric(10,6),
    mg_fe numeric(10,6),
    al_fe numeric(10,6),
    si_fe numeric(10,6),
    s_fe numeric(10,6),
    ca_fe numeric(10,6),
    ti_fe numeric(10,6),
    cr_fe numeric(10,6),
    ni_fe numeric(10,6),
    cu_fe numeric(10,6),
    alpha_m_lasp numeric(10,6),
    alpha_m_lasp_err numeric(10,6),
    moon_angle numeric(5,1),
    lunardate smallint,
    moon_flg character varying(10)
);

--
-- Name: mstellar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE mstellar (
    obsid bigint,
    uid character varying(32),
    gp_id bigint,
    designation character varying(19),
    obsdate date,
    lmjd integer,
    mjd integer,
    planid character varying(40),
    spid integer,
    fiberid integer,
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    snru numeric(6,2),
    snrg numeric(6,2),
    snrr numeric(6,2),
    snri numeric(6,2),
    snrz numeric(6,2),
    class character varying(20),
    subclass character varying(20),
    z numeric(21,10),
    z_err numeric(21,10),
    ps_id bigint,
    mag_ps_g numeric(16,10),
    mag_ps_r numeric(16,10),
    mag_ps_i numeric(16,10),
    mag_ps_z numeric(16,10),
    mag_ps_y numeric(16,10),
    gaia_source_id character varying(25),
    gaia_g_mean_mag numeric(13,8),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    teff numeric(10,2),
    teff_err numeric(8,2),
    logg numeric(10,3),
    logg_err numeric(8,3),
    m_h numeric(12,6),
    m_h_err numeric(12,6),
    ewha numeric(12,6),
    ewha_err numeric(12,6),
    tio5 numeric(12,6),
    cah2 numeric(12,6),
    cah3 numeric(12,6),
    tio1 numeric(12,6),
    tio2 numeric(12,6),
    tio3 numeric(12,6),
    tio4 numeric(12,6),
    cah1 numeric(12,6),
    caoh numeric(12,6),
    tio5_err numeric(12,6),
    cah2_err numeric(12,6),
    cah3_err numeric(12,6),
    tio1_err numeric(12,6),
    tio2_err numeric(12,6),
    tio3_err numeric(12,6),
    tio4_err numeric(12,6),
    cah1_err numeric(12,6),
    caoh_err numeric(12,6),
    zeta numeric(12,6),
    zeta_err numeric(12,6),
    type numeric(8,2),
    na numeric(10,6)
);

--
-- Name: plan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE planinfo (
    pid integer,
    obsdate date,
    planid character varying(40),
    ra numeric(11,7),
    dec numeric(11,7),
    mag numeric(5,2),
    seeing numeric(5,2),
    exptime character varying(120),
    lmjm bigint
);

--
-- Name: qso; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE qso (
    obsid bigint,
    uid character varying(32),
    gp_id bigint,
    designation character varying(19),
    obsdate date,
    lmjd integer,
    mjd integer,
    planid character varying(40),
    spid integer,
    fiberid integer,
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    snru numeric(6,2),
    snrg numeric(6,2),
    snrr numeric(6,2),
    snri numeric(6,2),
    snrz numeric(6,2),
    class character varying(20),
    subclass character varying(20),
    z numeric(21,10),
    z_err numeric(21,10),
    ps_id bigint,
    mag_ps_g numeric(16,10),
    mag_ps_r numeric(16,10),
    mag_ps_i numeric(16,10),
    mag_ps_z numeric(16,10),
    mag_ps_y numeric(16,10),
    gaia_source_id character varying(25),
    gaia_g_mean_mag numeric(13,8),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    sn_ratio_conti numeric(32,12),
    fe_uv_norm numeric(32,12),
    fe_uv_fwhm numeric(32,12),
    fe_uv_shift numeric(32,12),
    fe_op_norm numeric(32,12),
    fe_op_fwhm numeric(32,12),
    fe_op_shift numeric(32,12),
    pl_norm numeric(32,12),
    pl_slope numeric(32,12),
    balmer_norm numeric(32,12),
    balmer_teff integer,
    balmer_tau_e numeric(32,12),
    poly_a numeric(32,12),
    poly_b numeric(32,12),
    poly_c numeric(32,12),
    l1350 numeric(32,12),
    l3000 numeric(32,12),
    l5100 numeric(32,12),
    line_name_1 character varying(5),
    fitting_status_1 integer,
    min_chi2_1 numeric(32,12),
    red_chi2_1 numeric(32,12),
    ndof_1 integer,
    line_name_2 character varying(5),
    fitting_status_2 integer,
    min_chi2_2 numeric(32,12),
    red_chi2_2 numeric(32,12),
    ndof_2 integer,
    line_name_3 character varying(5),
    fitting_status_3 integer,
    min_chi2_3 numeric(32,12),
    red_chi2_3 numeric(32,12),
    ndof_3 integer,
    line_name_4 character varying(5),
    fitting_status_4 integer,
    min_chi2_4 numeric(32,12),
    red_chi2_4 numeric(32,12),
    ndof_4 integer,
    line_name_5 character varying(1),
    fitting_status_5 integer,
    min_chi2_5 integer,
    red_chi2_5 integer,
    ndof_5 integer,
    line_name_6 character varying(1),
    fitting_status_6 integer,
    min_chi2_6 integer,
    red_chi2_6 integer,
    ndof_6 integer,
    lya_br_1_peak_flux numeric(32,12),
    lya_br_1_peak_wavelength numeric(32,12),
    lya_br_1_sigma numeric(32,12),
    lya_na_1_peak_flux numeric(32,12),
    lya_na_1_peak_wavelength numeric(32,12),
    lya_na_1_sigma numeric(32,12),
    civ_br_1_peak_flux numeric(32,12),
    civ_br_1_peak_wavelength numeric(32,12),
    civ_br_1_sigma numeric(32,12),
    civ_na_1_peak_flux numeric(32,12),
    civ_na_1_peak_wavelength numeric(32,12),
    civ_na_1_sigma numeric(32,12),
    ciii_br_1_peak_flux numeric(32,12),
    ciii_br_1_peak_wavelength numeric(32,12),
    ciii_br_1_sigma numeric(32,12),
    ciii_br_2_peak_flux numeric(32,12),
    ciii_br_2_peak_wavelength numeric(32,12),
    ciii_na_1_peak_flux integer,
    ciii_na_1_peak_wavelength integer,
    ciii_na_1_sigma integer,
    ciii_na_2_peak_flux integer,
    ciii_na_2_peak_wavelength integer,
    ciii_na_2_sigma integer,
    mgii_br_1_peak_flux numeric(32,12),
    mgii_br_1_peak_wavelength numeric(32,12),
    mgii_br_1_sigma numeric(32,12),
    mgii_na_1_peak_flux numeric(32,12),
    mgii_na_1_peak_wavelength numeric(32,12),
    mgii_na_1_sigma numeric(32,12),
    mgii_na_2_peak_flux numeric(32,12),
    mgii_na_2_peak_wavelength numeric(32,12),
    mgii_na_2_sigma numeric(32,12),
    hb_br_1_peak_flux numeric(32,12),
    hb_br_1_peak_wavelength numeric(32,12),
    hb_br_1_sigma numeric(32,12),
    hb_na_1_peak_flux numeric(32,12),
    hb_na_1_peak_wavelength numeric(32,12),
    hb_na_1_sigma numeric(32,12),
    oiii4959_1_peak_flux numeric(32,12),
    oiii4959_1_peak_wavelength numeric(32,12),
    oiii4959_1_sigma numeric(32,12),
    oiii5007_1_peak_flux numeric(32,12),
    oiii5007_1_peak_wavelength numeric(32,12),
    oiii5007_1_sigma numeric(32,12),
    ha_br_1_peak_flux numeric(32,12),
    ha_br_1_peak_wavelength numeric(32,12),
    ha_br_1_sigma numeric(32,12),
    ha_br_2_peak_flux numeric(32,12),
    ha_br_2_peak_wavelength numeric(32,12),
    ha_br_2_sigma numeric(32,12),
    ha_br_3_peak_flux numeric(32,12),
    ha_br_3_peak_wavelength numeric(32,12),
    ha_br_3_sigma numeric(32,12),
    ha_na_1_peak_flux numeric(32,12),
    ha_na_1_peak_wavelength numeric(32,12),
    ha_na_1_sigma numeric(32,12),
    nii6549_1_peak_flux numeric(32,12),
    nii6549_1_peak_wavelength numeric(32,12),
    nii6549_1_sigma numeric(32,12),
    nii6585_1_peak_flux numeric(32,12),
    nii6585_1_peak_wavelength numeric(32,12),
    nii6585_1_sigma numeric(32,12),
    sii6718_1_peak_flux numeric(32,12),
    sii6718_1_peak_wavelength numeric(32,12),
    sii6718_1_sigma numeric(32,12),
    sii6732_1_peak_flux numeric(32,12),
    sii6732_1_peak_wavelength numeric(32,12),
    sii6732_1_sigma numeric(32,12),
    lya_fwhm numeric(32,12),
    lya_sigma numeric(32,12),
    lya_ew numeric(32,12),
    lya_peak_wavelength numeric(32,12),
    lya_area numeric(32,12),
    civ_fwhm numeric(32,12),
    civ_sigma numeric(32,12),
    civ_ew numeric(32,12),
    civ_peak_wavelength numeric(32,12),
    civ_area numeric(32,12),
    ciii_fwhm numeric(32,12),
    ciii_sigma numeric(32,12),
    ciii_ew numeric(32,12),
    ciii_peak_wavelength numeric(32,12),
    ciii_area numeric(32,12),
    mgii_fwhm numeric(32,12),
    mgii_sigma numeric(32,12),
    mgii_ew numeric(32,12),
    mgii_peak_wavelength numeric(32,12),
    mgii_area numeric(32,12),
    hb_fwhm numeric(32,12),
    hb_sigma numeric(32,12),
    hb_ew numeric(32,12),
    hb_peak_wavelength numeric(32,12),
    hb_area numeric(32,12),
    ha_fwhm numeric(32,12),
    ha_sigma numeric(32,12),
    ha_ew numeric(32,12),
    ha_peak_wavelength numeric(32,12),
    ha_area numeric(32,12)
);

--
-- Name: stellar; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE stellar (
    obsid bigint,
    uid character varying(32),
    gp_id bigint,
    designation character varying(19),
    obsdate date,
    lmjd integer,
    mjd integer,
    planid character varying(40),
    spid integer,
    fiberid integer,
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    snru numeric(6,2),
    snrg numeric(6,2),
    snrr numeric(6,2),
    snri numeric(6,2),
    snrz numeric(6,2),
    class character varying(20),
    subclass character varying(20),
    z numeric(21,10),
    z_err numeric(21,10),
    ps_id bigint,
    mag_ps_g numeric(16,10),
    mag_ps_r numeric(16,10),
    mag_ps_i numeric(16,10),
    mag_ps_z numeric(16,10),
    mag_ps_y numeric(16,10),
    gaia_source_id character varying(25),
    gaia_g_mean_mag numeric(13,8),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    teff numeric(10,2),
    teff_err numeric(8,2),
    logg numeric(10,3),
    logg_err numeric(8,3),
    feh numeric(10,3),
    feh_err numeric(8,3),
    rv numeric(10,2),
    rv_err numeric(8,2),
    alpha_m numeric(10,6),
    alpha_m_err numeric(10,6)
);

--
-- Name: wd; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE wd (
    obsid bigint,
    uid character varying(32),
    gp_id bigint,
    designation character varying(19),
    obsdate date,
    lmjd integer,
    mjd integer,
    planid character varying(40),
    spid integer,
    fiberid integer,
    ra_obs numeric(16,10),
    dec_obs numeric(16,10),
    snru numeric(6,2),
    snrg numeric(6,2),
    snrr numeric(6,2),
    snri numeric(6,2),
    snrz numeric(6,2),
    class character varying(20),
    subclass character varying(20),
    z numeric(21,10),
    z_err numeric(21,10),
    ps_id bigint,
    mag_ps_g numeric(16,10),
    mag_ps_r numeric(16,10),
    mag_ps_i numeric(16,10),
    mag_ps_z numeric(16,10),
    mag_ps_y numeric(16,10),
    gaia_source_id character varying(25),
    gaia_g_mean_mag numeric(13,8),
    tsource character varying(16),
    fibertype character varying(10),
    tfrom character varying(60),
    tcomment character varying(80),
    [offsets] integer,
    offsets_v numeric(6,3),
    ra numeric(16,10),
    dec numeric(16,10),
    wd_subclass character varying(10),
    teff numeric(10,2),
    teff_err numeric(8,2),
    logg numeric(10,3),
    logg_err numeric(8,3)
);
