--=================================================================
--   spSphericalUninstall.sql
--	 2007-06-11 Tamas Budavari
-------------------------------------------------------------------
-- Drops the HTM and Spherical SQL/CLR routines and assemblies
-------------------------------------------------------------------
-- History:
--		2007-10-20: Spherical routines go to schema Sph
-------------------------------------------------------------------

--====================================================================
PRINT '*** DROP ***'
PRINT 'Dropping SQL routines...'
--
BEGIN TRY DROP FUNCTION fHtmVersion END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmEq END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmXyz END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmGetString END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmCoverCircleEq END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmCoverCircleXyz END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmGetCenterPoint END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmGetCornerPoints END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fDistanceEq END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fDistanceXyz END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmEqToXyz END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmXyzToEq END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmCoverRegion END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmCoverRegionError END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmCoverRegionList END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmCoverRegionAdvanced END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION fHtmCoverBinaryAdvanced END TRY BEGIN CATCH END CATCH
--
BEGIN TRY DROP FUNCTION dbo.fGetVersion END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGetVersions END TRY BEGIN CATCH END CATCH
--
BEGIN TRY DROP FUNCTION dbo.fGetArea END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGetArcs END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGetOutlineArcs END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGetPatches END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGetHalfspaces END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGetConvexes END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGetRegionString END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGetRegionStringBin END TRY BEGIN CATCH END CATCH
--
BEGIN TRY DROP FUNCTION dbo.fSimplify END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fSimplifyAdvanced END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fSimplifyQuery END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fSimplifyQueryAdvanced END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fSimplifyBinary END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fSimplifyBinaryAdvanced END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fSimplifyString END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fSimplifyStringAdvanced END TRY BEGIN CATCH END CATCH
--
BEGIN TRY DROP FUNCTION dbo.fGrow END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGrowArc END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGrowAdvanced END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fUnion END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fUnionAdvanced END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fUnionQuery END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fIntersect END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fIntersectAdvanced END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fIntersectQuery END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fDiff END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fDiffAdvanced END TRY BEGIN CATCH END CATCH
--
BEGIN TRY DROP FUNCTION dbo.fRegionContainsXYZ END TRY BEGIN CATCH END CATCH
--
BEGIN TRY DROP FUNCTION dbo.fConvexAddHalfspace END TRY BEGIN CATCH END CATCH
--
BEGIN TRY DROP FUNCTION dbo.fGetHtmRanges END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP FUNCTION dbo.fGetHtmRangesAdvanced END TRY BEGIN CATCH END CATCH
--
BEGIN TRY DROP PROCEDURE spSphSyncRegion END TRY BEGIN CATCH END CATCH
BEGIN TRY DROP PROCEDURE dbo.spSyncRegion END TRY BEGIN CATCH END CATCH
--
BEGIN TRY
	DROP ASSEMBLY [SphericalSql]
	PRINT 'Dropped assembly SphericalSql'
END TRY
BEGIN CATCH END CATCH
--
BEGIN TRY
	DROP ASSEMBLY [SphericalHTM]
	PRINT 'Dropped assembly SphericalHTM'
END TRY
BEGIN CATCH END CATCH
--
BEGIN TRY
	DROP ASSEMBLY [SphericalQuickhull]
	PRINT 'Dropped assembly SphericalQuickhull'
END TRY
BEGIN CATCH END CATCH
--
BEGIN TRY
	DROP ASSEMBLY [Spherical.Quickhull]
	PRINT 'Dropped assembly Spherical.Quickhull'
END TRY
BEGIN CATCH END CATCH
--
BEGIN TRY
	DROP ASSEMBLY [SphericalIO]
	PRINT 'Dropped assembly SphericalIO'
END TRY
BEGIN CATCH END CATCH
--
BEGIN TRY
	DROP ASSEMBLY [SphericalLib]
	PRINT 'Dropped assembly SphericalLib'
END TRY
BEGIN CATCH END CATCH
--
