USE [master]
GO

/****** Object:  Database [sueDB]    Script Date: 3/22/2017 3:12:17 PM ******/
CREATE DATABASE [sueDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sueDB', FILENAME = N'C:\data\data1\sql_db\sueDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'sueDB_log', FILENAME = N'C:\data\data2\sql_db\sueDB_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [sueDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sueDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sueDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sueDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sueDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sueDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sueDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [sueDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sueDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sueDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sueDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sueDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sueDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sueDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sueDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sueDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sueDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sueDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sueDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sueDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sueDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sueDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sueDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sueDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sueDB] SET RECOVERY FULL 
GO

ALTER DATABASE [sueDB] SET  MULTI_USER 
GO

ALTER DATABASE [sueDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sueDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sueDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sueDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [sueDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sueDB] SET  READ_WRITE 
GO


