USE [master]
GO

/*
--1800MB per DATAFG
--325 MB for PRIMARY
--18500 per for SPEC
*/

/****** Object:  Database [DR14x]   Script Date: 4/3/2018 1:43:49 PM ******/
CREATE DATABASE [DR14x]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DR14x_PRIMARY', FILENAME = N'C:\data\data1\sql_db\PRIMARY.MDF' , SIZE = 325MB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%), 

 FILEGROUP [DATAFG] 
( NAME = N'DATA_01', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_01.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_02', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_02.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_03', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_03.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_04', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_04.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_05', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_05.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_06', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_06.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_07', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_07.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_08', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_08.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_09', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_09.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_10', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_10.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_11', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_11.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ),
( NAME = N'DATA_12', FILENAME = N'C:\data\data1\sql_db\DR14x\DATA_12.ndf' , SIZE = 1800MB , MAXSIZE = UNLIMITED, FILEGROWTH = 50MB ), 
 
 
 FILEGROUP [SPEC] 
( NAME = N'SPEC_01', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_01.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_02', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_02.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_03', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_03.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_04', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_04.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_05', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_05.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_06', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_06.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_07', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_07.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_08', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_08.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_09', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_09.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_10', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_10.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_11', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_11.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ),
( NAME = N'SPEC_12', FILENAME = N'C:\data\data1\sql_db\DR14x\SPEC_12.ndf' , SIZE = 18500MB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB ) 
 LOG ON
( NAME = N'DR14x_Log1', FILENAME = N'G:\DR14x_Log1.ldf' , SIZE = 100MB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'DR14x_Log2', FILENAME = N'G:\DR14x_Log2.ldf' , SIZE = 100MB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'DR14x_Log3', FILENAME = N'G:\DR14x_Log3.ldf' , SIZE = 100MB , MAXSIZE = 2048GB , FILEGROWTH = 10%), 
( NAME = N'DR14x_Log4', FILENAME = N'G:\DR14x_Log4.ldf' , SIZE = 100MB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO



IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DR14x].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DR14x] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DR14x] SET ANSI_NULLS ON 
GO

ALTER DATABASE [DR14x] SET ANSI_PADDING ON 
GO

ALTER DATABASE [DR14x] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [DR14x] SET ARITHABORT ON 
GO

ALTER DATABASE [DR14x] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DR14x] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DR14x] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DR14x] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DR14x] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DR14x] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [DR14x] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DR14x] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [DR14x] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DR14x] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DR14x] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DR14x] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DR14x] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DR14x] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DR14x] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DR14x] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DR14x] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DR14x] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DR14x] SET  MULTI_USER 
GO

ALTER DATABASE [DR14x] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DR14x] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DR14x] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DR14x] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DR14x] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DR14x] SET QUERY_STORE = ON
GO

ALTER DATABASE [DR14x] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1024, QUERY_CAPTURE_MODE = ALL, SIZE_BASED_CLEANUP_MODE = AUTO)
GO

USE [DR14x]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [DR14x] SET  READ_WRITE 
GO


