USE [master]
GO

drop database minidb2
go


/****** Object:  Database [minidb2]    Script Date: 10/26/2022 3:53:31 PM ******/
CREATE DATABASE [minidb2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'minidb2', FILENAME = N'D:\sql_db\minidb2.mdf' , SIZE = 10048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10048KB ), 
 FILEGROUP [MINIDB] 
( NAME = N'minidb01', FILENAME = N'D:\sql_db\minidb01.ndf' , SIZE = 3072000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ),
( NAME = N'minidb02', FILENAME = N'D:\sql_db\minidb02.ndf' , SIZE = 3072000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ),
( NAME = N'minidb03', FILENAME = N'D:\sql_db\minidb03.ndf' , SIZE = 3072000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ),
( NAME = N'minidb04', FILENAME = N'D:\sql_db\minidb04.ndf' , SIZE = 3072000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ),
( NAME = N'minidb05', FILENAME = N'D:\sql_db\minidb05.ndf' , SIZE = 3072000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ),
( NAME = N'minidb06', FILENAME = N'D:\sql_db\minidb06.ndf' , SIZE = 3072000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ),
( NAME = N'minidb07', FILENAME = N'D:\sql_db\minidb07.ndf' , SIZE = 3072000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB ),
( NAME = N'minidb08', FILENAME = N'D:\sql_db\minidb08.ndf' , SIZE = 3072000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )

 LOG ON 
( NAME = N'minidb2_log', FILENAME = N'E:\sql_db\minidb2_log.ldf' , SIZE = 5382144KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [minidb2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [minidb2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [minidb2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [minidb2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [minidb2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [minidb2] SET ARITHABORT OFF 
GO

ALTER DATABASE [minidb2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [minidb2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [minidb2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [minidb2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [minidb2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [minidb2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [minidb2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [minidb2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [minidb2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [minidb2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [minidb2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [minidb2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [minidb2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [minidb2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [minidb2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [minidb2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [minidb2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [minidb2] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [minidb2] SET  MULTI_USER 
GO

ALTER DATABASE [minidb2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [minidb2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [minidb2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [minidb2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [minidb2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [minidb2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [minidb2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [minidb2] SET  READ_WRITE 
GO


