USE [minidb2]
GO

/****** Object:  Table [dbo].[dr19_allwise]    Script Date: 1/30/2025 12:39:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--(((w1mpro - w2mpro)))

drop table if exists dr19_allwise
CREATE TABLE [dbo].[dr19_allwise](
	[designation] [varchar](20) NULL,
	[ra] [numeric](10, 7) NULL,
	[dec] [numeric](9, 7) NULL,
	[sigra] [numeric](7, 4) NULL,
	[sigdec] [numeric](7, 4) NULL,
	[sigradec] [numeric](8, 4) NULL,
	[glon] [numeric](10, 7) NULL,
	[glat] [numeric](9, 7) NULL,
	[elon] [numeric](10, 7) NULL,
	[elat] [numeric](9, 7) NULL,
	[wx] [numeric](7, 3) NULL,
	[wy] [numeric](7, 3) NULL,
	[cntr] [bigint] NOT NULL,
	[source_id] [varchar](28) NULL,
	[coadd_id] [varchar](20) NULL,
	[src] [int] NULL,
	[w1mpro] [numeric](5, 3) NULL,
	[w1sigmpro] [numeric](4, 3) NULL,
	[w1snr] [numeric](7, 1) NULL,
	[w1rchi2] [real] NULL,
	[w2mpro] [numeric](5, 3) NULL,
	[w1mpro_w2mpro] as (w1mpro - w2mpro) persisted,
	[w2sigmpro] [numeric](4, 3) NULL,
	[w2snr] [numeric](7, 1) NULL,
	[w2rchi2] [real] NULL,
	[w3mpro] [numeric](5, 3) NULL,
	[w3sigmpro] [numeric](4, 3) NULL,
	[w3snr] [numeric](7, 1) NULL,
	[w3rchi2] [real] NULL,
	[w4mpro] [numeric](5, 3) NULL,
	[w4sigmpro] [numeric](4, 3) NULL,
	[w4snr] [numeric](7, 1) NULL,
	[w4rchi2] [real] NULL,
	[rchi2] [real] NULL,
	[nb] [int] NULL,
	[na] [int] NULL,
	[w1sat] [numeric](4, 3) NULL,
	[w2sat] [numeric](4, 3) NULL,
	[w3sat] [numeric](4, 3) NULL,
	[w4sat] [numeric](4, 3) NULL,
	[satnum] [varchar](4) NULL,
	[ra_pm] [numeric](10, 7) NULL,
	[dec_pm] [numeric](9, 7) NULL,
	[sigra_pm] [numeric](7, 4) NULL,
	[sigdec_pm] [numeric](7, 4) NULL,
	[sigradec_pm] [numeric](8, 4) NULL,
	[pmra] [int] NULL,
	[sigpmra] [int] NULL,
	[pmdec] [int] NULL,
	[sigpmdec] [int] NULL,
	[w1rchi2_pm] [real] NULL,
	[w2rchi2_pm] [real] NULL,
	[w3rchi2_pm] [real] NULL,
	[w4rchi2_pm] [real] NULL,
	[rchi2_pm] [real] NULL,
	[pmcode] [varchar](5) NULL,
	[cc_flags] [varchar](4) NULL,
	[rel] [varchar](1) NULL,
	[ext_flg] [int] NULL,
	[var_flg] [varchar](4) NULL,
	[ph_qual] [varchar](4) NULL,
	[det_bit] [int] NULL,
	[moon_lev] [varchar](4) NULL,
	[w1nm] [int] NULL,
	[w1m] [int] NULL,
	[w2nm] [int] NULL,
	[w2m] [int] NULL,
	[w3nm] [int] NULL,
	[w3m] [int] NULL,
	[w4nm] [int] NULL,
	[w4m] [int] NULL,
	[w1cov] [numeric](6, 3) NULL,
	[w2cov] [numeric](6, 3) NULL,
	[w3cov] [numeric](6, 3) NULL,
	[w4cov] [numeric](6, 3) NULL,
	[w1cc_map] [int] NULL,
	[w1cc_map_str] [varchar](9) NULL,
	[w2cc_map] [int] NULL,
	[w2cc_map_str] [varchar](9) NULL,
	[w3cc_map] [int] NULL,
	[w3cc_map_str] [varchar](9) NULL,
	[w4cc_map] [int] NULL,
	[w4cc_map_str] [varchar](9) NULL,
	[best_use_cntr] [bigint] NULL,
	[ngrp] [smallint] NULL,
	[w1flux] [real] NULL,
	[w1sigflux] [real] NULL,
	[w1sky] [numeric](8, 3) NULL,
	[w1sigsk] [numeric](6, 3) NULL,
	[w1conf] [numeric](8, 3) NULL,
	[w2flux] [real] NULL,
	[w2sigflux] [real] NULL,
	[w2sky] [numeric](8, 3) NULL,
	[w2sigsk] [numeric](6, 3) NULL,
	[w2conf] [numeric](8, 3) NULL,
	[w3flux] [real] NULL,
	[w3sigflux] [real] NULL,
	[w3sky] [numeric](8, 3) NULL,
	[w3sigsk] [numeric](6, 3) NULL,
	[w3conf] [numeric](8, 3) NULL,
	[w4flux] [real] NULL,
	[w4sigflux] [real] NULL,
	[w4sky] [numeric](8, 3) NULL,
	[w4sigsk] [numeric](6, 3) NULL,
	[w4conf] [numeric](8, 3) NULL,
	[w1mag] [numeric](5, 3) NULL,
	[w1sigm] [numeric](4, 3) NULL,
	[w1flg] [int] NULL,
	[w1mcor] [numeric](4, 3) NULL,
	[w2mag] [numeric](5, 3) NULL,
	[w2sigm] [numeric](4, 3) NULL,
	[w2flg] [int] NULL,
	[w2mcor] [numeric](4, 3) NULL,
	[w3mag] [numeric](5, 3) NULL,
	[w3sigm] [numeric](4, 3) NULL,
	[w3flg] [int] NULL,
	[w3mcor] [numeric](4, 3) NULL,
	[w4mag] [numeric](5, 3) NULL,
	[w4sigm] [numeric](4, 3) NULL,
	[w4flg] [int] NULL,
	[w4mcor] [numeric](4, 3) NULL,
	[w1mag_1] [numeric](5, 3) NULL,
	[w1sigm_1] [numeric](4, 3) NULL,
	[w1flg_1] [int] NULL,
	[w2mag_1] [numeric](5, 3) NULL,
	[w2sigm_1] [numeric](4, 3) NULL,
	[w2flg_1] [int] NULL,
	[w3mag_1] [numeric](5, 3) NULL,
	[w3sigm_1] [numeric](4, 3) NULL,
	[w3flg_1] [int] NULL,
	[w4mag_1] [numeric](5, 3) NULL,
	[w4sigm_1] [numeric](4, 3) NULL,
	[w4flg_1] [int] NULL,
	[w1mag_2] [numeric](5, 3) NULL,
	[w1sigm_2] [numeric](4, 3) NULL,
	[w1flg_2] [int] NULL,
	[w2mag_2] [numeric](5, 3) NULL,
	[w2sigm_2] [numeric](4, 3) NULL,
	[w2flg_2] [int] NULL,
	[w3mag_2] [numeric](5, 3) NULL,
	[w3sigm_2] [numeric](4, 3) NULL,
	[w3flg_2] [int] NULL,
	[w4mag_2] [numeric](5, 3) NULL,
	[w4sigm_2] [numeric](4, 3) NULL,
	[w4flg_2] [int] NULL,
	[w1mag_3] [numeric](5, 3) NULL,
	[w1sigm_3] [numeric](4, 3) NULL,
	[w1flg_3] [int] NULL,
	[w2mag_3] [numeric](5, 3) NULL,
	[w2sigm_3] [numeric](4, 3) NULL,
	[w2flg_3] [int] NULL,
	[w3mag_3] [numeric](5, 3) NULL,
	[w3sigm_3] [numeric](4, 3) NULL,
	[w3flg_3] [int] NULL,
	[w4mag_3] [numeric](5, 3) NULL,
	[w4sigm_3] [numeric](4, 3) NULL,
	[w4flg_3] [int] NULL,
	[w1mag_4] [numeric](5, 3) NULL,
	[w1sigm_4] [numeric](4, 3) NULL,
	[w1flg_4] [int] NULL,
	[w2mag_4] [numeric](5, 3) NULL,
	[w2sigm_4] [numeric](4, 3) NULL,
	[w2flg_4] [int] NULL,
	[w3mag_4] [numeric](5, 3) NULL,
	[w3sigm_4] [numeric](4, 3) NULL,
	[w3flg_4] [int] NULL,
	[w4mag_4] [numeric](5, 3) NULL,
	[w4sigm_4] [numeric](4, 3) NULL,
	[w4flg_4] [int] NULL,
	[w1mag_5] [numeric](5, 3) NULL,
	[w1sigm_5] [numeric](4, 3) NULL,
	[w1flg_5] [int] NULL,
	[w2mag_5] [numeric](5, 3) NULL,
	[w2sigm_5] [numeric](4, 3) NULL,
	[w2flg_5] [int] NULL,
	[w3mag_5] [numeric](5, 3) NULL,
	[w3sigm_5] [numeric](4, 3) NULL,
	[w3flg_5] [int] NULL,
	[w4mag_5] [numeric](5, 3) NULL,
	[w4sigm_5] [numeric](4, 3) NULL,
	[w4flg_5] [int] NULL,
	[w1mag_6] [numeric](5, 3) NULL,
	[w1sigm_6] [numeric](4, 3) NULL,
	[w1flg_6] [int] NULL,
	[w2mag_6] [numeric](5, 3) NULL,
	[w2sigm_6] [numeric](4, 3) NULL,
	[w2flg_6] [int] NULL,
	[w3mag_6] [numeric](5, 3) NULL,
	[w3sigm_6] [numeric](4, 3) NULL,
	[w3flg_6] [int] NULL,
	[w4mag_6] [numeric](5, 3) NULL,
	[w4sigm_6] [numeric](4, 3) NULL,
	[w4flg_6] [int] NULL,
	[w1mag_7] [numeric](5, 3) NULL,
	[w1sigm_7] [numeric](4, 3) NULL,
	[w1flg_7] [int] NULL,
	[w2mag_7] [numeric](5, 3) NULL,
	[w2sigm_7] [numeric](4, 3) NULL,
	[w2flg_7] [int] NULL,
	[w3mag_7] [numeric](5, 3) NULL,
	[w3sigm_7] [numeric](4, 3) NULL,
	[w3flg_7] [int] NULL,
	[w4mag_7] [numeric](5, 3) NULL,
	[w4sigm_7] [numeric](4, 3) NULL,
	[w4flg_7] [int] NULL,
	[w1mag_8] [numeric](5, 3) NULL,
	[w1sigm_8] [numeric](4, 3) NULL,
	[w1flg_8] [int] NULL,
	[w2mag_8] [numeric](5, 3) NULL,
	[w2sigm_8] [numeric](4, 3) NULL,
	[w2flg_8] [int] NULL,
	[w3mag_8] [numeric](5, 3) NULL,
	[w3sigm_8] [numeric](4, 3) NULL,
	[w3flg_8] [int] NULL,
	[w4mag_8] [numeric](5, 3) NULL,
	[w4sigm_8] [numeric](4, 3) NULL,
	[w4flg_8] [int] NULL,
	[w1magp] [numeric](5, 3) NULL,
	[w1sigp1] [numeric](5, 3) NULL,
	[w1sigp2] [numeric](5, 3) NULL,
	[w1k] [numeric](4, 3) NULL,
	[w1ndf] [int] NULL,
	[w1mlq] [numeric](4, 2) NULL,
	[w1mjdmin] [numeric](13, 8) NULL,
	[w1mjdmax] [numeric](13, 8) NULL,
	[w1mjdmean] [numeric](13, 8) NULL,
	[w2magp] [numeric](5, 3) NULL,
	[w2sigp1] [numeric](5, 3) NULL,
	[w2sigp2] [numeric](5, 3) NULL,
	[w2k] [numeric](4, 3) NULL,
	[w2ndf] [int] NULL,
	[w2mlq] [numeric](4, 2) NULL,
	[w2mjdmin] [numeric](13, 8) NULL,
	[w2mjdmax] [numeric](13, 8) NULL,
	[w2mjdmean] [numeric](13, 8) NULL,
	[w3magp] [numeric](5, 3) NULL,
	[w3sigp1] [numeric](5, 3) NULL,
	[w3sigp2] [numeric](5, 3) NULL,
	[w3k] [numeric](4, 3) NULL,
	[w3ndf] [int] NULL,
	[w3mlq] [numeric](4, 2) NULL,
	[w3mjdmin] [numeric](13, 8) NULL,
	[w3mjdmax] [numeric](13, 8) NULL,
	[w3mjdmean] [numeric](13, 8) NULL,
	[w4magp] [numeric](5, 3) NULL,
	[w4sigp1] [numeric](5, 3) NULL,
	[w4sigp2] [numeric](5, 3) NULL,
	[w4k] [numeric](4, 3) NULL,
	[w4ndf] [int] NULL,
	[w4mlq] [numeric](4, 2) NULL,
	[w4mjdmin] [numeric](13, 8) NULL,
	[w4mjdmax] [numeric](13, 8) NULL,
	[w4mjdmean] [numeric](13, 8) NULL,
	[rho12] [int] NULL,
	[rho23] [int] NULL,
	[rho34] [int] NULL,
	[q12] [int] NULL,
	[q23] [int] NULL,
	[q34] [int] NULL,
	[xscprox] [numeric](7, 2) NULL,
	[w1rsemi] [numeric](7, 2) NULL,
	[w1ba] [numeric](3, 2) NULL,
	[w1pa] [numeric](5, 2) NULL,
	[w1gmag] [numeric](5, 3) NULL,
	[w1gerr] [numeric](4, 3) NULL,
	[w1gflg] [int] NULL,
	[w2rsemi] [numeric](7, 2) NULL,
	[w2ba] [numeric](3, 2) NULL,
	[w2pa] [numeric](5, 2) NULL,
	[w2gmag] [numeric](5, 3) NULL,
	[w2gerr] [numeric](4, 3) NULL,
	[w2gflg] [int] NULL,
	[w3rsemi] [numeric](7, 2) NULL,
	[w3ba] [numeric](3, 2) NULL,
	[w3pa] [numeric](5, 2) NULL,
	[w3gmag] [numeric](5, 3) NULL,
	[w3gerr] [numeric](4, 3) NULL,
	[w3gflg] [int] NULL,
	[w4rsemi] [numeric](7, 2) NULL,
	[w4ba] [numeric](3, 2) NULL,
	[w4pa] [numeric](5, 2) NULL,
	[w4gmag] [numeric](5, 3) NULL,
	[w4gerr] [numeric](4, 3) NULL,
	[w4gflg] [int] NULL,
	[tmass_key] [int] NULL,
	[r_2mass] [numeric](5, 3) NULL,
	[pa_2mass] [numeric](4, 1) NULL,
	[n_2mass] [int] NULL,
	[j_m_2mass] [numeric](5, 3) NULL,
	[j_msig_2mass] [numeric](4, 3) NULL,
	[h_m_2mass] [numeric](5, 3) NULL,
	[h_msig_2mass] [numeric](4, 3) NULL,
	[k_m_2mass] [numeric](5, 3) NULL,
	[k_msig_2mass] [numeric](4, 3) NULL,
	[x] [numeric](17, 16) NULL,
	[y] [numeric](17, 16) NULL,
	[z] [numeric](17, 16) NULL,
	[spt_ind] [int] NULL,
	[htm20] [bigint] NULL,
	[cx] [float] NULL,
	[cy] [float] NULL,
	[cz] [float] NULL,
	[htmid]  AS ([dbo].[fhtmeq]([ra],[dec])) PERSISTED
) ON [PRIMARY]
GO


