CREATE TABLE [dbo].[DBObjects](
	[name] [varchar](128) NOT NULL,
	[type] [varchar](64) NOT NULL,
	[access] [varchar](8) NOT NULL,
	[description] [varchar](256) NOT NULL,
	[text] [varchar](7200) NOT NULL,
	[rank] [int] NOT NULL,
)


INSERT DBObjects VALUES('dbo.dr19_best_brightest','U','U',' Catalog from Kevin Schlaufman for the selection of bright metal-poor stars from the method of Schlaufman and Casey (2014): https://ui.adsabs.harvard.edu/abs/2014ApJ...797...13S/abstract. WISE values from WHICH CATALOG, 2MASS values from 2MASS point source catalog. ','','0');
INSERT DBObjects VALUES('dbo.dr19_catalog','U','U',' The table stores the results of the cross-match used for dr19 targeting. All entries in this table are expected to be unique physical objects drawn from one or more parent catalogues. The dr19_catalog_to_ tables provide the relationship between dr19_catalog objects and their parent catalogue counterparts. ','','0');
INSERT DBObjects VALUES('dbo.dr19_gaia_dr2_ruwe','U','U',' Table from Gaia DR2 containing the Renormalised Unit Weight Error (RUWE) associated to each source in gaia_source. See https://gea.esac.esa.int/archive/documentation/GDR2/Gaia_archive/chap_datamodel/sec_dm_main_tables/ssec_dm_ruwe.html for more detailed descriptions of the columns ','','0');
INSERT DBObjects VALUES('dbo.dr19_panstarrs1','U','U',' A copy of the PanSTARRS1-dr2 catalogue provided by E. Magnier. Based on the internal IPP database representation mainyaned by IfA, U. Hawaii. Column names may differ from publically available catalogues hosted at MAST (mapping provided in column descriptions). The SDSS-V copy of this database is derived from a combination of the PS1-dr2 StackObjectThin and ObjectThin tables (https://outerspace.stsci.edu/display/PANSTARRS/PS1+Database+object+and+detection+tables). The catalogue contains PSF, Kron, and Aper measurements based on stacked and forced warp photometry, and expressed as fluxes, including measurements are made of low-significance detections. The average exposure (chip) measurements are expressed in magnitudes since photometry is not measured at this stage for sources with S/N < 5, so there should not be any negative fluxes. Magnitudes are on the AB system, fluxes are in Janskys. Conversion to AB mags is via: mag = 8.9 - 2.5*log10(flux). ','','0');
INSERT DBObjects VALUES('dbo.dr19_sdss_dr16_specobj','U','U',' This table contains the list of all SDSS optical spectra for a given data release, with associated parameters from the 2D and 1D pipelines for each. The table contains both the BOSS and SDSS spectrograph data. The database representation is derived from the flat file information described here: <a href=''https://data.sdss.org/datamodel/files/SPECTRO_REDUX/specObj.html''>https://data.sdss.org/datamodel/files/SPECTRO_REDUX/specObj.html</a> Note: the order of the columns in this documentation may not match the order of the columns in the database table. ','','0');
INSERT DBObjects VALUES('dbo.dr19_sdss_dr17_specobj','U','U',' This table contains the list of all SDSS optical spectra for a given data release, with associated parameters from the 2D and 1D pipelines for each. The table contains both the BOSS and SDSS spectrograph data. The database representation is derived from the flat file information described here: <a href=''https://data.sdss.org/datamodel/files/SPECTRO_REDUX/specObj.html''>https://data.sdss.org/datamodel/files/SPECTRO_REDUX/specObj.html</a> Note: the order of the columns in this documentation may not match the order of the columns in the database table. ','','0');
INSERT DBObjects VALUES('dbo.dr19_sdss_id_flat','U','U',' This table includes associations between sdss_id identifiers and the best matched catalogid for each catalogue cross-match. Unlike dr19_sdss_id_stacked, this table contains multiple rows per sdss_id, one for each cross-match association. When multiple sdss_ids are associated with the same catalogid, the one with the lowest rank (rank=1) should be preferred. ',' Note: The sdss_id match was extended internally for a more recent crossmatch not  yet part of the publicly released data. As such, the ra/dec_sdss_id columns may  differ from the catalogid coordinates. ','0');
INSERT DBObjects VALUES('dbo.dr19_sdss_id_stacked','U','U',' This table includes associations between sdss_id identifiers and the matched catalogids for each catalogue cross-match. The table contains one row per sdss_id with columns for each catalogid version. However, catalogids may be associated with multiple sdss_id. dr19_sdss_id_flat is a pivoted/flattened version of this table and contains information about the preferred sdss_id for a catalogid. ',' Note: The sdss_id match was extended internally for a more recent crossmatch not  yet part of the publicly released data. As such, the ra/dec_sdss_id columns may  differ from the catalogid coordinates. ','0');
INSERT DBObjects VALUES('dbo.dr19_skies_v1','U','U',' This table stores the positions used as blank sky regions for DR19 targetting. The sky regions are selected by dividing the sky in tiles of HEALpix nside 32. Each tile is then subdivided in candidate regions of HEALpix nside 32768 and the pixels that meet the isolation requirements are considered valid skies. This process is repeated for a number of all-sky catalogues. See <a href=''https://sdss.org/dr19/targeting/fps/sky/''> for further details of the process by which suitable sky locations are selected in SDSS-V/FPS. This version of the skies catalog was used for v0.1 target selection. The skies_v2 catalog was used for v0.5 and subsequent target selections. ','','0');
INSERT DBObjects VALUES('dbo.dr19_skies_v2','U','U',' This table stores the positions used as blank sky regions for dr19 targetting. The sky regions are selected by dividing the sky in tiles of HEALpix nside 32. Each tile is then subdivided in candidate regions of HEALpix nside 32768 and the pixels that meet the isolation requirements are considered valid skies. This process is repeated for a number of all-sky catalogues. See <a href=''https://sdss.org/dr19/targeting/fps/sky/''> for further details of the process by which suitable sky locations are selected in SDSS-V/FPS. ','','0');
INSERT DBObjects VALUES('dbo.dr19_target','U','U',' This table stores the targets associated with dr19 target selection cartons. Note that the targets in this table are unique, but a target can be associated with multiple cartons. That many-to-many relationship is encoded in the dr19_carton_to_target table. ','','0');
INSERT DBObjects VALUES('dbo.dr19_xmm_om_suss_4_1','U','U',' The 2018 release of the XMM OM Serendipitous Ultraviolet Source Survey (XMM-SUSS4.1) Catalog. For full details, please see https://heasarc.gsfc.nasa.gov/W3Browse/all/xmmomsuob.html and the original catalog paper (Page et al. 2012; https://academic.oup.com/mnras/article/426/2/903/976665) ','','0');
INSERT DBObjects VALUES('dbo.dr19_unwise','U','U',' The unWISE catalog, containing the positions and fluxes of approximately two billion objects observed by the Wide-field Infrared Survey Explorer (WISE). See Schlafly et al. (2019). The original catalogs are hosted at https://catalog.unwise.me/catalogs.html ','','0');
INSERT DBObjects VALUES('dbo.dr19_tic_v8','U','U',' The Eighth version (v8.0) of the TESS Input Catalogue (<a href=''https://outerspace.stsci.edu/display/TESS/TIC+v8+and+CTL+v8.xx+Data+Release+Notes''></a>). This catalogue is used in v0.5 target selection as a form of internal cross-match between the objects found in difference input catalogues. ','','0');
INSERT DBObjects VALUES('dbo.dr19_tess_toi_v05','U','U',' This catalog contains targets that recieved the 2 minute cadence during the TESS Mission, are TESS Objects of Interest (TOI) or Community TESS Objects of Interest (CTOI). The contents of this catalog were derived from the MIT TESS website (https://tess.mit.edu/public/target_lists/target_lists.html) and the ExoFOP website https://exofop.ipac.caltech.edu/tess/index.php. These targets were updated on 2020-11-24. ','','0');
INSERT DBObjects VALUES('dbo.dr19_tess_toi','U','U',' This catalog contains targets that recieved the 2 minute cadence during the TESS Mission, are TESS Objects of Interest (TOI) or Community TESS Objects of Interest (CTOI). The contents of this catalog were derived from the MIT TESS website (https://tess.mit.edu/public/target_lists/target_lists.html) and the ExoFOP website https://exofop.ipac.caltech.edu/tess/index.php. These targets were updated on 2020-04-02. ','','0');



CREATE TABLE [dbo].[DBColumns](
	[tablename] [varchar](128) NOT NULL,
	[name] [varchar](64) NOT NULL,
	[unit] [varchar](64) NOT NULL,
	[ucd] [varchar](128) NOT NULL,
	[enum] [varchar](64) NOT NULL,
	[description] [varchar](2000) NOT NULL,
	[rank] [int] NOT NULL,
)

-- there seem to be several issues with the doc strings for dr19_allstar_dr17_synspec_rev1, these were just the ones that broke the insert
INSERT DBColumns VALUES('dbo.dr19_allstar_dr17_synspec_rev1','apstar_id','ns].[sc','','','Unique ASPCAP identifier: apogee.','0');
INSERT DBColumns VALUES('dbo.dr19_allstar_dr17_synspec_rev1','aspcap_id','ns].[sc].APSTAR_VERS.LOC.STAR, where [ns] is for APOGEE North/South, [sc','','','Unique apStar identifier: apogee.','0');
INSERT DBColumns VALUES('dbo.dr19_allstar_dr17_synspec_rev1','alpha_m','alpha/M] from ASPCAP analysis of combined spectrum (from PARAM) [dex','','','','0');
INSERT DBColumns VALUES('dbo.dr19_mangadapall','sfr_1re','2012, ARAA, 50, 531], citing Murphy et al. [2011, ApJ, 737, 67] and Hao et al. [2011, ApJ, 741, 124]; Kroupa IMF), where L_{Ha} = 4-Ç EML_FLUX_1RE (LDIST_Z)^{2} and ''''no'''' attentuation correction has been applied. [h^{-2} M_{sun}/yr','','','Simple estimate of the star-formation rate within 1 effective radius based on the Gaussian-fitted Ha flux; log(SFR) = log L_{Ha} - 41.27 (Kennicutt &amp;amp; Evans','0');
INSERT DBColumns VALUES('dbo.dr19_mangadapall','sfr_tot','2012, ARAA, 50, 531], citing Murphy et al. [2011, ApJ, 737, 67] and Hao et al. [2011, ApJ, 741, 124]; Kroupa IMF), where L_{Ha} = 4-Ç EML_FLUX_TOT (LDIST_Z)^{2} and ''''no'''' attentuation correction has been applied. [h^{-2} M_{sun}/yr','','','Simple estimate of the star-formation rate within the IFU field-of-view based on the Gaussian-fitted Ha flux; log(SFR) = log L_{Ha} - 41.27 (Kennicutt &amp;amp; Evans','0');
