USE [minidb2]
GO

/****** Object:  Table [dbo].[dr19_gaia_dr2_source]    Script Date: 1/30/2025 12:31:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
drop table if exists dr19_gaia_dr2_source
CREATE TABLE [dbo].[dr19_gaia_dr2_source](
	[solution_id] [bigint] NULL,
	[designation] [varchar](500) NULL,
	[source_id] [bigint] NOT NULL,
	[random_index] [bigint] NULL,
	[ref_epoch] [float] NULL,
	[ra] [float] NULL,
	[ra_error] [float] NULL,
	[dec] [float] NULL,
	[dec_error] [float] NULL,
	[parallax] [float] NULL,
	[parallax_error] [float] NULL,
	[parallax_over_error] [real] NULL,
	[parallax_parallax_error] as (parallax - parallax_error) persisted,
	[pmra] [float] NULL,
	[pmra_error] [float] NULL,
	[pmdec] [float] NULL,
	[pmdec_error] [float] NULL,
	[ra_dec_corr] [real] NULL,
	[ra_parallax_corr] [real] NULL,
	[ra_pmra_corr] [real] NULL,
	[ra_pmdec_corr] [real] NULL,
	[dec_parallax_corr] [real] NULL,
	[dec_pmra_corr] [real] NULL,
	[dec_pmdec_corr] [real] NULL,
	[parallax_pmra_corr] [real] NULL,
	[parallax_pmdec_corr] [real] NULL,
	[pmra_pmdec_corr] [real] NULL,
	[astrometric_n_obs_al] [int] NULL,
	[astrometric_n_obs_ac] [int] NULL,
	[astrometric_n_good_obs_al] [int] NULL,
	[astrometric_n_bad_obs_al] [int] NULL,
	[astrometric_gof_al] [real] NULL,
	[astrometric_chi2_al] [real] NULL,
	[astrometric_excess_noise] [float] NULL,
	[astrometric_excess_noise_sig] [float] NULL,
	[astrometric_params_solved] [int] NULL,
	[astrometric_primary_flag] [bit] NULL,
	[astrometric_weight_al] [real] NULL,
	[astrometric_pseudo_colour] [float] NULL,
	[astrometric_pseudo_colour_error] [float] NULL,
	[mean_varpi_factor_al] [real] NULL,
	[astrometric_matched_observations] [smallint] NULL,
	[visibility_periods_used] [smallint] NULL,
	[astrometric_sigma5d_max] [real] NULL,
	[frame_rotator_object_type] [int] NULL,
	[matched_observations] [smallint] NULL,
	[duplicated_source] [bit] NULL,
	[phot_g_n_obs] [int] NULL,
	[phot_g_mean_flux] [float] NULL,
	[phot_g_mean_flux_error] [float] NULL,
	[phot_g_mean_flux_over_error] [real] NULL,
	[phot_g_mean_mag] [real] NULL,
	[phot_bp_n_obs] [int] NULL,
	[phot_bp_mean_flux] [float] NULL,
	[phot_bp_mean_flux_error] [float] NULL,
	[phot_bp_mean_flux_over_error] [real] NULL,
	[phot_bp_mean_mag] [real] NULL,
	[phot_rp_n_obs] [int] NULL,
	[phot_rp_mean_flux] [float] NULL,
	[phot_rp_mean_flux_error] [float] NULL,
	[phot_rp_mean_flux_over_error] [real] NULL,
	[phot_rp_mean_mag] [real] NULL,
	[phot_bp_rp_excess_factor] [real] NULL,
	[phot_proc_mode] [int] NULL,
	[bp_rp] [real] NULL,
	[bp_g] [real] NULL,
	[g_rp] [real] NULL,
	[radial_velocity] [float] NULL,
	[radial_velocity_error] [float] NULL,
	[rv_nb_transits] [int] NULL,
	[rv_template_teff] [real] NULL,
	[rv_template_logg] [real] NULL,
	[rv_template_fe_h] [real] NULL,
	[phot_variable_flag] [varchar](500) NULL,
	[l] [float] NULL,
	[b] [float] NULL,
	[ecl_lon] [float] NULL,
	[ecl_lat] [float] NULL,
	[priam_flags] [bigint] NULL,
	[teff_val] [real] NULL,
	[teff_percentile_lower] [real] NULL,
	[teff_percentile_upper] [real] NULL,
	[a_g_val] [real] NULL,
	[a_g_percentile_lower] [real] NULL,
	[a_g_percentile_upper] [real] NULL,
	[e_bp_min_rp_val] [real] NULL,
	[e_bp_min_rp_percentile_lower] [real] NULL,
	[e_bp_min_rp_percentile_upper] [real] NULL,
	[flame_flags] [bigint] NULL,
	[radius_val] [real] NULL,
	[radius_percentile_lower] [real] NULL,
	[radius_percentile_upper] [real] NULL,
	[lum_val] [real] NULL,
	[lum_percentile_lower] [real] NULL,
	[lum_percentile_upper] [real] NULL,
	[cx] [float] NULL,
	[cy] [float] NULL,
	[cz] [float] NULL,
	[htmid]  AS ([dbo].[fhtmeq]([ra],[dec])) PERSISTED
) ON [PRIMARY]
GO


