USE [minidb2]
GO

/****** Object:  Table [dbo].[dr19_guvcat]    Script Date: 1/30/2025 12:36:54 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--(((fuv_mag - nuv_mag)));
drop table if exists dr19_guvcat
CREATE TABLE [dbo].[dr19_guvcat](
	[objid] [bigint] NOT NULL,
	[photoextractid] [bigint] NULL,
	[mpstype] [varchar](500) NULL,
	[avaspra] [float] NULL,
	[avaspdec] [float] NULL,
	[fexptime] [real] NULL,
	[nexptime] [real] NULL,
	[ra] [float] NULL,
	[dec] [float] NULL,
	[glon] [float] NULL,
	[glat] [float] NULL,
	[tilenum] [int] NULL,
	[img] [int] NULL,
	[subvisit] [int] NULL,
	[fov_radius] [real] NULL,
	[type] [int] NULL,
	[band] [int] NULL,
	[e_bv] [real] NULL,
	[istherespectrum] [smallint] NULL,
	[chkobj_type] [smallint] NULL,
	[fuv_mag] [real] NULL,
	[fuv_magerr] [real] NULL,
	[nuv_mag] [real] NULL,
	[nuv_magerr] [real] NULL,
	[fuv_mag_nuv_mag] as (fuv_mag - nuv_mag) persisted,
	[fuv_mag_auto] [real] NULL,
	[fuv_magerr_auto] [real] NULL,
	[nuv_mag_auto] [real] NULL,
	[nuv_magerr_auto] [real] NULL,
	[fuv_mag_aper_4] [real] NULL,
	[fuv_magerr_aper_4] [real] NULL,
	[nuv_mag_aper_4] [real] NULL,
	[nuv_magerr_aper_4] [real] NULL,
	[fuv_mag_aper_6] [real] NULL,
	[fuv_magerr_aper_6] [real] NULL,
	[nuv_mag_aper_6] [real] NULL,
	[nuv_magerr_aper_6] [real] NULL,
	[fuv_artifact] [smallint] NULL,
	[nuv_artifact] [smallint] NULL,
	[fuv_flags] [smallint] NULL,
	[nuv_flags] [smallint] NULL,
	[fuv_flux] [real] NULL,
	[fuv_fluxerr] [real] NULL,
	[nuv_flux] [real] NULL,
	[nuv_fluxerr] [real] NULL,
	[fuv_x_image] [real] NULL,
	[fuv_y_image] [real] NULL,
	[nuv_x_image] [real] NULL,
	[nuv_y_image] [real] NULL,
	[fuv_fwhm_image] [real] NULL,
	[nuv_fwhm_image] [real] NULL,
	[fuv_fwhm_world] [real] NULL,
	[nuv_fwhm_world] [real] NULL,
	[nuv_class_star] [real] NULL,
	[fuv_class_star] [real] NULL,
	[nuv_ellipticity] [real] NULL,
	[fuv_ellipticity] [real] NULL,
	[nuv_theta_j2000] [real] NULL,
	[nuv_errtheta_j2000] [real] NULL,
	[fuv_theta_j2000] [real] NULL,
	[fuv_errtheta_j2000] [real] NULL,
	[fuv_ncat_fwhm_image] [real] NULL,
	[fuv_ncat_flux_radius_3] [real] NULL,
	[nuv_kron_radius] [real] NULL,
	[nuv_a_world] [real] NULL,
	[nuv_b_world] [real] NULL,
	[fuv_kron_radius] [real] NULL,
	[fuv_a_world] [real] NULL,
	[fuv_b_world] [real] NULL,
	[nuv_weight] [real] NULL,
	[fuv_weight] [real] NULL,
	[prob] [real] NULL,
	[sep] [real] NULL,
	[nuv_poserr] [real] NULL,
	[fuv_poserr] [real] NULL,
	[ib_poserr] [real] NULL,
	[nuv_pperr] [real] NULL,
	[fuv_pperr] [real] NULL,
	[corv] [varchar](500) NULL,
	[grank] [smallint] NULL,
	[ngrank] [smallint] NULL,
	[primgid] [bigint] NULL,
	[groupgid] [varchar](500) NULL,
	[grankdist] [smallint] NULL,
	[ngrankdist] [bigint] NULL,
	[primgiddist] [bigint] NULL,
	[groupgiddist] [varchar](500) NULL,
	[groupgidtot] [varchar](500) NULL,
	[difffuv] [real] NULL,
	[diffnuv] [real] NULL,
	[difffuvdist] [real] NULL,
	[diffnuvdist] [real] NULL,
	[sepas] [real] NULL,
	[sepasdist] [real] NULL,
	[inlargeobj] [varchar](500) NULL,
	[largeobjsize] [real] NULL,
	[cx] [float] NULL,
	[cy] [float] NULL,
	[cz] [float] NULL
) ON [PRIMARY]
GO


