USE [BestDR19]
GO

/****** Object:  Table [dbo].[mangaDRPall]    Script Date: 7/7/2025 11:44:14 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[mangaDRPall](
	[plate] [int] NOT NULL,
	[ifudsgn] [varchar](40) NOT NULL,
	[plateifu] [varchar](40) NOT NULL,
	[mangaid] [varchar](40) NOT NULL,
	[versdrp2] [varchar](40) NOT NULL,
	[versdrp3] [varchar](40) NOT NULL,
	[verscore] [varchar](40) NOT NULL,
	[versutil] [varchar](40) NOT NULL,
	[versprim] [varchar](40) NOT NULL,
	[platetyp] [varchar](40) NOT NULL,
	[srvymode] [varchar](40) NOT NULL,
	[objra] [float] NOT NULL,
	[objdec] [float] NOT NULL,
	[ifuglon] [float] NOT NULL,
	[ifuglat] [float] NOT NULL,
	[ifura] [float] NOT NULL,
	[ifudec] [float] NOT NULL,
	[ebvgal] [real] NOT NULL,
	[nexp] [int] NOT NULL,
	[exptime] [real] NOT NULL,
	[drp3qual] [int] NOT NULL,
	[bluesn2] [real] NOT NULL,
	[redsn2] [real] NOT NULL,
	[harname] [varchar](60) NOT NULL,
	[frlplug] [int] NOT NULL,
	[cartid] [varchar](40) NOT NULL,
	[designid] [int] NOT NULL,
	[cenra] [float] NOT NULL,
	[cendec] [float] NOT NULL,
	[airmsmin] [real] NOT NULL,
	[airmsmed] [real] NOT NULL,
	[airmsmax] [real] NOT NULL,
	[seemin] [real] NOT NULL,
	[seemed] [real] NOT NULL,
	[seemax] [real] NOT NULL,
	[transmin] [real] NOT NULL,
	[transmed] [real] NOT NULL,
	[transmax] [real] NOT NULL,
	[mjdmin] [int] NOT NULL,
	[mjdmed] [int] NOT NULL,
	[mjdmax] [int] NOT NULL,
	[gfwhm] [real] NOT NULL,
	[rfwhm] [real] NOT NULL,
	[ifwhm] [real] NOT NULL,
	[zfwhm] [real] NOT NULL,
	[mngtarg1] [bigint] NOT NULL,
	[mngtarg2] [bigint] NOT NULL,
	[mngtarg3] [bigint] NOT NULL,
	[catidnum] [bigint] NOT NULL,
	[plttarg] [varchar](40) NOT NULL,
	[manga_tileid] [int] NOT NULL,
	[nsa_iauname] [varchar](20) NOT NULL,
	[ifutargetsize] [int] NOT NULL,
	[ifudesignsize] [int] NOT NULL,
	[ifudesignwrongsize] [int] NOT NULL,
	[z] [real] NOT NULL,
	[zmin] [real] NOT NULL,
	[zmax] [real] NOT NULL,
	[szmin] [real] NOT NULL,
	[szmax] [real] NOT NULL,
	[ezmin] [real] NOT NULL,
	[ezmax] [real] NOT NULL,
	[probs] [real] NOT NULL,
	[pweight] [real] NOT NULL,
	[psweight] [real] NOT NULL,
	[psrweight] [real] NOT NULL,
	[sweight] [real] NOT NULL,
	[srweight] [real] NOT NULL,
	[eweight] [real] NOT NULL,
	[esweight] [real] NOT NULL,
	[esrweight] [real] NOT NULL,
	[nsa_field] [int] NOT NULL,
	[nsa_run] [int] NOT NULL,
	[nsa_camcol] [int] NOT NULL,
	[nsa_version] [varchar](10) NOT NULL,
	[nsa_nsaid] [int] NOT NULL,
	[nsa_nsaid_v1b] [int] NOT NULL,
	[nsa_z] [real] NOT NULL,
	[nsa_zdist] [real] NOT NULL,
	[nsa_elpetro_mass] [real] NOT NULL,
	[nsa_elpetro_absmag_f] [real] NOT NULL,
	[nsa_elpetro_absmag_n] [real] NOT NULL,
	[nsa_elpetro_absmag_u] [real] NOT NULL,
	[nsa_elpetro_absmag_g] [real] NOT NULL,
	[nsa_elpetro_absmag_r] [real] NOT NULL,
	[nsa_elpetro_absmag_i] [real] NOT NULL,
	[nsa_elpetro_absmag_z] [real] NOT NULL,
	[nsa_elpetro_amivar_f] [real] NOT NULL,
	[nsa_elpetro_amivar_n] [real] NOT NULL,
	[nsa_elpetro_amivar_u] [real] NOT NULL,
	[nsa_elpetro_amivar_g] [real] NOT NULL,
	[nsa_elpetro_amivar_r] [real] NOT NULL,
	[nsa_elpetro_amivar_i] [real] NOT NULL,
	[nsa_elpetro_amivar_z] [real] NOT NULL,
	[nsa_elpetro_flux_f] [real] NOT NULL,
	[nsa_elpetro_flux_n] [real] NOT NULL,
	[nsa_elpetro_flux_u] [real] NOT NULL,
	[nsa_elpetro_flux_g] [real] NOT NULL,
	[nsa_elpetro_flux_r] [real] NOT NULL,
	[nsa_elpetro_flux_i] [real] NOT NULL,
	[nsa_elpetro_flux_z] [real] NOT NULL,
	[nsa_elpetro_flux_ivar_f] [real] NOT NULL,
	[nsa_elpetro_flux_ivar_n] [real] NOT NULL,
	[nsa_elpetro_flux_ivar_u] [real] NOT NULL,
	[nsa_elpetro_flux_ivar_g] [real] NOT NULL,
	[nsa_elpetro_flux_ivar_r] [real] NOT NULL,
	[nsa_elpetro_flux_ivar_i] [real] NOT NULL,
	[nsa_elpetro_flux_ivar_z] [real] NOT NULL,
	[nsa_elpetro_th50_r] [real] NOT NULL,
	[nsa_elpetro_phi] [real] NOT NULL,
	[nsa_elpetro_ba] [real] NOT NULL,
	[nsa_sersic_mass] [real] NOT NULL,
	[nsa_sersic_absmag_f] [real] NOT NULL,
	[nsa_sersic_absmag_n] [real] NOT NULL,
	[nsa_sersic_absmag_u] [real] NOT NULL,
	[nsa_sersic_absmag_g] [real] NOT NULL,
	[nsa_sersic_absmag_r] [real] NOT NULL,
	[nsa_sersic_absmag_i] [real] NOT NULL,
	[nsa_sersic_absmag_z] [real] NOT NULL,
	[nsa_sersic_flux_f] [real] NOT NULL,
	[nsa_sersic_flux_n] [real] NOT NULL,
	[nsa_sersic_flux_u] [real] NOT NULL,
	[nsa_sersic_flux_g] [real] NOT NULL,
	[nsa_sersic_flux_r] [real] NOT NULL,
	[nsa_sersic_flux_i] [real] NOT NULL,
	[nsa_sersic_flux_z] [real] NOT NULL,
	[nsa_sersic_flux_ivar_f] [real] NOT NULL,
	[nsa_sersic_flux_ivar_n] [real] NOT NULL,
	[nsa_sersic_flux_ivar_u] [real] NOT NULL,
	[nsa_sersic_flux_ivar_g] [real] NOT NULL,
	[nsa_sersic_flux_ivar_r] [real] NOT NULL,
	[nsa_sersic_flux_ivar_i] [real] NOT NULL,
	[nsa_sersic_flux_ivar_z] [real] NOT NULL,
	[nsa_sersic_th50] [real] NOT NULL,
	[nsa_sersic_phi] [real] NOT NULL,
	[nsa_sersic_ba] [real] NOT NULL,
	[nsa_sersic_n] [real] NOT NULL,
	[nsa_petro_flux_f] [real] NOT NULL,
	[nsa_petro_flux_n] [real] NOT NULL,
	[nsa_petro_flux_u] [real] NOT NULL,
	[nsa_petro_flux_g] [real] NOT NULL,
	[nsa_petro_flux_r] [real] NOT NULL,
	[nsa_petro_flux_i] [real] NOT NULL,
	[nsa_petro_flux_z] [real] NOT NULL,
	[nsa_petro_flux_ivar_f] [real] NOT NULL,
	[nsa_petro_flux_ivar_n] [real] NOT NULL,
	[nsa_petro_flux_ivar_u] [real] NOT NULL,
	[nsa_petro_flux_ivar_g] [real] NOT NULL,
	[nsa_petro_flux_ivar_r] [real] NOT NULL,
	[nsa_petro_flux_ivar_i] [real] NOT NULL,
	[nsa_petro_flux_ivar_z] [real] NOT NULL,
	[nsa_petro_th50] [real] NOT NULL,
	[nsa_extinction_f] [real] NOT NULL,
	[nsa_extinction_n] [real] NOT NULL,
	[nsa_extinction_u] [real] NOT NULL,
	[nsa_extinction_g] [real] NOT NULL,
	[nsa_extinction_r] [real] NOT NULL,
	[nsa_extinction_i] [real] NOT NULL,
	[nsa_extinction_z] [real] NOT NULL,
	[htmID] [bigint] NOT NULL,
 CONSTRAINT [pk_mangaDRPall_plateIFU] PRIMARY KEY CLUSTERED 
(
	[plateifu] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [SPEC]
) ON [SPEC]
GO

ALTER TABLE [dbo].[mangaDRPall]  WITH NOCHECK ADD  CONSTRAINT [fk_mangaDRPall_mangaID_mangaTarg] FOREIGN KEY([mangaid])
REFERENCES [dbo].[mangaTarget] ([mangaID])
GO

ALTER TABLE [dbo].[mangaDRPall] CHECK CONSTRAINT [fk_mangaDRPall_mangaID_mangaTarg]
GO


