DROP TABLE IF EXISTS dbo.dr19_sdss_id_flat
CREATE TABLE dbo.dr19_sdss_id_flat (
    sdss_id bigint,
    catalogid bigint,
    version_id smallint,
    ra_sdss_id double precision,
    dec_sdss_id double precision,
    n_associated smallint,
    ra_catalogid double precision,
    dec_catalogid double precision,
    pk bigint NOT NULL,
    rank integer
);

DROP TABLE IF EXISTS dbo.dr19_sdss_id_stacked
CREATE TABLE dbo.dr19_sdss_id_stacked (
    catalogid21 bigint,
    catalogid25 bigint,
    ra_sdss_id double precision,
    dec_sdss_id double precision,
    sdss_id bigint NOT NULL
);


DROP TABLE IF EXISTS dbo.dr19_sdss_id_to_catalog
CREATE TABLE dbo.dr19_sdss_id_to_catalog (
    pk bigint,
    sdss_id bigint,
    catalogid bigint,
    version_id integer,
    lead varchar(500),
    allstar_dr17_synspec_rev1__apstar_id varchar(500),
    allwise__cntr bigint,
    bhm_rm_v0__pk bigint,
    bhm_rm_v0_2__pk bigint,
    catwise__source_id varchar(25),
    catwise2020__source_id varchar(25),
    gaia_dr2_source__source_id bigint,
    gaia_dr3_source__source_id bigint,
    glimpse__pk bigint,
    guvcat__objid bigint,
    legacy_survey_dr10__ls_id bigint,
    legacy_survey_dr8__ls_id bigint,
    mangatarget__mangaid varchar(20),
    marvels_dr11_star__starname varchar,
    marvels_dr12_star__pk bigint,
    mastar_goodstars__mangaid varchar(25),
    panstarrs1__catid_objid bigint,
    ps1_g18__objid bigint,
    sdss_dr13_photoobj__objid bigint,
    sdss_dr17_specobj__specobjid varchar,
    skymapper_dr1_1__object_id bigint,
    skymapper_dr2__object_id bigint,
    supercosmos__objid bigint,
    tic_v8__id bigint,
    twomass_psc__pts_key integer,
    tycho2__designation varchar(500),
    unwise__unwise_objid varchar(500)
);

DROP TABLE IF EXISTS dbo.dr19_mangatarget
CREATE TABLE dbo.dr19_mangatarget (
    catalog_ra double precision,
    catalog_dec double precision,
    nsa_z real,
    nsa_zdist real,
    nsa_elpetro_mass real,
    nsa_elpetro_absmag_f real,
    nsa_elpetro_absmag_n real,
    nsa_elpetro_absmag_u real,
    nsa_elpetro_absmag_g real,
    nsa_elpetro_absmag_r real,
    nsa_elpetro_absmag_i real,
    nsa_elpetro_absmag_z real,
    nsa_elpetro_amivar_f real,
    nsa_elpetro_amivar_n real,
    nsa_elpetro_amivar_u real,
    nsa_elpetro_amivar_g real,
    nsa_elpetro_amivar_r real,
    nsa_elpetro_amivar_i real,
    nsa_elpetro_amivar_z real,
    nsa_elpetro_flux_f real,
    nsa_elpetro_flux_n real,
    nsa_elpetro_flux_u real,
    nsa_elpetro_flux_g real,
    nsa_elpetro_flux_r real,
    nsa_elpetro_flux_i real,
    nsa_elpetro_flux_z real,
    nsa_elpetro_flux_ivar_f real,
    nsa_elpetro_flux_ivar_n real,
    nsa_elpetro_flux_ivar_u real,
    nsa_elpetro_flux_ivar_g real,
    nsa_elpetro_flux_ivar_r real,
    nsa_elpetro_flux_ivar_i real,
    nsa_elpetro_flux_ivar_z real,
    nsa_elpetro_th50_r_original real,
    nsa_elpetro_th50_f real,
    nsa_elpetro_th50_n real,
    nsa_elpetro_th50_u real,
    nsa_elpetro_th50_g real,
    nsa_elpetro_th50_r real,
    nsa_elpetro_th50_i real,
    nsa_elpetro_th50_z real,
    nsa_elpetro_phi real,
    nsa_elpetro_ba real,
    nsa_sersic_mass real,
    nsa_sersic_absmag_f real,
    nsa_sersic_absmag_n real,
    nsa_sersic_absmag_u real,
    nsa_sersic_absmag_g real,
    nsa_sersic_absmag_r real,
    nsa_sersic_absmag_i real,
    nsa_sersic_absmag_z real,
    nsa_sersic_amivar_f real,
    nsa_sersic_amivar_n real,
    nsa_sersic_amivar_u real,
    nsa_sersic_amivar_g real,
    nsa_sersic_amivar_r real,
    nsa_sersic_amivar_i real,
    nsa_sersic_amivar_z real,
    nsa_sersic_flux_f real,
    nsa_sersic_flux_n real,
    nsa_sersic_flux_u real,
    nsa_sersic_flux_g real,
    nsa_sersic_flux_r real,
    nsa_sersic_flux_i real,
    nsa_sersic_flux_z real,
    nsa_sersic_flux_ivar_f real,
    nsa_sersic_flux_ivar_n real,
    nsa_sersic_flux_ivar_u real,
    nsa_sersic_flux_ivar_g real,
    nsa_sersic_flux_ivar_r real,
    nsa_sersic_flux_ivar_i real,
    nsa_sersic_flux_ivar_z real,
    nsa_sersic_th50 real,
    nsa_sersic_phi real,
    nsa_sersic_ba real,
    nsa_sersic_n real,
    nsa_petro_flux_f real,
    nsa_petro_flux_n real,
    nsa_petro_flux_u real,
    nsa_petro_flux_g real,
    nsa_petro_flux_r real,
    nsa_petro_flux_i real,
    nsa_petro_flux_z real,
    nsa_petro_flux_ivar_f real,
    nsa_petro_flux_ivar_n real,
    nsa_petro_flux_ivar_u real,
    nsa_petro_flux_ivar_g real,
    nsa_petro_flux_ivar_r real,
    nsa_petro_flux_ivar_i real,
    nsa_petro_flux_ivar_z real,
    nsa_petro_th50 real,
    nsa_extinction_f real,
    nsa_extinction_n real,
    nsa_extinction_u real,
    nsa_extinction_g real,
    nsa_extinction_r real,
    nsa_extinction_i real,
    nsa_extinction_z real,
    nsa_iauname varchar(20),
    nsa_subdir varchar(128),
    nsa_pid integer,
    nsa_nsaid integer,
    catind integer,
    manga_target1 bigint,
    mangaid varchar(20) NOT NULL,
    zmin real,
    zmax real,
    szmin real,
    szmax real,
    ezmin real,
    ezmax real,
    probs real,
    pweight real,
    sweight real,
    srweight real,
    eweight real,
    psrweight real,
    esrweight real,
    psweight real,
    esweight real,
    ranflag bit(1),
    manga_tileids_0 integer,
    manga_tileids_1 integer,
    manga_tileids_2 integer,
    manga_tileids_3 integer,
    manga_tileids_4 integer,
    manga_tileids_5 integer,
    manga_tileids_6 integer,
    manga_tileids_7 integer,
    manga_tileids_8 integer,
    manga_tileids_9 integer,
    manga_tileids_10 integer,
    manga_tileids_11 integer,
    manga_tileids_12 integer,
    manga_tileids_13 integer,
    manga_tileids_14 integer,
    manga_tileids_15 integer,
    manga_tileids_16 integer,
    manga_tileids_17 integer,
    manga_tileids_18 integer,
    manga_tileids_19 integer,
    manga_tileids_20 integer,
    manga_tileids_21 integer,
    manga_tileids_22 integer,
    manga_tileids_23 integer,
    manga_tileids_24 integer,
    manga_tileids_25 integer,
    manga_tileids_26 integer,
    manga_tileids_27 integer,
    manga_tileids_28 integer,
    manga_tileids_29 integer,
    manga_tileid integer,
    tilera double precision,
    tiledec double precision,
    ifutargetsize smallint,
    ifudesignsize smallint,
    ifudesignwrongsize smallint,
    ifu_ra double precision,
    ifu_dec double precision,
    badphotflag bit(1),
    starflag bit(1),
    object_ra double precision,
    object_dec double precision,
    obsflag bit(1),
    catindanc integer,
    ifudesignsizemain smallint,
    ifuminsizeanc smallint,
    ifutargsizeanc smallint,
    manga_target3 bigint,
    priorityanc integer,
    unalloc smallint,
    specobjid varchar(500)
);

DROP TABLE IF EXISTS dbo.dr19_catalog_to_mastar_goodstars
CREATE TABLE dbo.dr19_catalog_to_mastar_goodstars (
    catalogid bigint NOT NULL,
    target_id varchar(255) NOT NULL,
    version_id smallint NOT NULL,
    distance double precision,
    best bit,
    planname_id varchar(500),
    added_by_phase smallint
);

DROP TABLE IF EXISTS dbo.dr19_mastar_goodstars
CREATE TABLE dbo.dr19_mastar_goodstars (
    drpver varchar(8),
    mprocver varchar(8),
    mangaid varchar(25) NOT NULL,
    minmjd integer,
    maxmjd integer,
    nvisits integer,
    nplates integer,
    ra double precision,
    "dec" double precision,
    epoch real,
    psfmag_1 real,
    psfmag_2 real,
    psfmag_3 real,
    psfmag_4 real,
    psfmag_5 real,
    mngtarg2 integer,
    input_logg real,
    input_teff real,
    input_fe_h real,
    input_alpha_m real,
    input_source varchar(16),
    photocat varchar(10)
);


DROP TABLE IF EXISTS dbo.dr19_mastar_goodvisits
CREATE TABLE dbo.dr19_mastar_goodvisits (
    drpver varchar(8),
    mprocver varchar(8),
    mangaid varchar(25),
    plate integer,
    ifudesign varchar(6),
    mjd integer,
    ifura double precision,
    ifudec double precision,
    ra double precision,
    "dec" double precision,
    epoch real,
    psfmag_1 real,
    psfmag_2 real,
    psfmag_3 real,
    psfmag_4 real,
    psfmag_5 real,
    mngtarg2 integer,
    exptime real,
    nexp_visit smallint,
    nvelgood smallint,
    heliov real,
    verr real,
    v_errcode smallint,
    heliov_visit real,
    verr_visit real,
    v_errcode_visit smallint,
    velvarflag smallint,
    dv_maxsig real,
    mjdqual integer,
    bprperr_sp real,
    nexp_used smallint,
    s2n real,
    s2n10 real,
    badpixfrac real,
    coord_source varchar(10),
    photocat varchar(10),
    pk bigint NOT NULL
);
DROP TABLE IF EXISTS dbo.dr19_allstar_dr17_synspec_rev1
CREATE TABLE dbo.dr19_allstar_dr17_synspec_rev1 (
    file varchar(500),
    apogee_id varchar(500),
    target_id varchar(500),
    apstar_id varchar(500) NOT NULL,
    aspcap_id varchar(500),
    telescope varchar(500),
    location_id integer,
    field varchar(500),
    alt_id varchar(500),
    ra double precision,
    "dec" double precision,
    glon double precision,
    glat double precision,
    j real,
    j_err real,
    h real,
    h_err real,
    k real,
    k_err real,
    src_h varchar(500),
    wash_m real,
    wash_m_err real,
    wash_t2 real,
    wash_t2_err real,
    ddo51 real,
    ddo51_err real,
    irac_3_6 real,
    irac_3_6_err real,
    irac_4_5 real,
    irac_4_5_err real,
    irac_5_8 real,
    irac_5_8_err real,
    irac_8_0 real,
    irac_8_0_err real,
    wise_4_5 real,
    wise_4_5_err real,
    targ_4_5 real,
    targ_4_5_err real,
    wash_ddo51_giant_flag integer,
    wash_ddo51_star_flag integer,
    targ_pmra real,
    targ_pmdec real,
    targ_pm_src varchar(500),
    ak_targ real,
    ak_targ_method varchar(500),
    ak_wise real,
    sfd_ebv real,
    apogee_target1 integer,
    apogee_target2 integer,
    apogee2_target1 integer,
    apogee2_target2 integer,
    apogee2_target3 integer,
    apogee2_target4 integer,
    targflags varchar(500),
    survey varchar(500),
    programname varchar(500),
    nvisits integer,
    snr real,
    snrev real,
    starflag bigint,
    starflags varchar(500),
    andflag bigint,
    andflags varchar(500),
    vhelio_avg real,
    vscatter real,
    verr real,
    rv_teff real,
    rv_logg real,
    rv_feh real,
    rv_alpha real,
    rv_carb real,
    rv_chi2 real,
    rv_ccfwhm real,
    rv_autofwhm real,
    rv_flag integer,
    n_components integer,
    meanfib real,
    sigfib real,
    min_h real,
    max_h real,
    min_jk real,
    max_jk real,
    gaiaedr3_source_id bigint,
    gaiaedr3_parallax real,
    gaiaedr3_parallax_error real,
    gaiaedr3_pmra real,
    gaiaedr3_pmra_error real,
    gaiaedr3_pmdec real,
    gaiaedr3_pmdec_error real,
    gaiaedr3_phot_g_mean_mag real,
    gaiaedr3_phot_bp_mean_mag real,
    gaiaedr3_phot_rp_mean_mag real,
    gaiaedr3_dr2_radial_velocity real,
    gaiaedr3_dr2_radial_velocity_error real,
    gaiaedr3_r_med_geo real,
    gaiaedr3_r_lo_geo real,
    gaiaedr3_r_hi_geo real,
    gaiaedr3_r_med_photogeo real,
    gaiaedr3_r_lo_photogeo real,
    gaiaedr3_r_hi_photogeo real,
    aspcap_grid varchar(500),
    fparam_grid varchar(500),
    chi2_grid varchar(500),
    fparam varchar(500),
    fparam_cov varchar(500),
    aspcap_chi2 real,
    param varchar(500),
    param_cov varchar(500),
    paramflag varchar(500),
    aspcapflag bigint,
    aspcapflags varchar(500),
    frac_badpix real,
    frac_lowsnr real,
    frac_sigsky real,
    felem varchar(500),
    felem_err varchar(500),
    x_h varchar(500),
    x_h_err varchar(500),
    x_m varchar(500),
    x_m_err varchar(500),
    elem_chi2 varchar(500),
    elemfrac varchar(500),
    elemflag varchar(500),
    extratarg integer,
    memberflag bigint,
    member varchar(500),
    x_h_spec varchar(500),
    x_m_spec varchar(500),
    teff real,
    teff_err real,
    logg real,
    logg_err real,
    m_h real,
    m_h_err real,
    alpha_m real,
    alpha_m_err real,
    vmicro real,
    vmacro real,
    vsini real,
    teff_spec real,
    logg_spec real,
    c_fe real,
    c_fe_spec real,
    c_fe_err real,
    c_fe_flag integer,
    ci_fe real,
    ci_fe_spec real,
    ci_fe_err real,
    ci_fe_flag integer,
    n_fe real,
    n_fe_spec real,
    n_fe_err real,
    n_fe_flag integer,
    o_fe real,
    o_fe_spec real,
    o_fe_err real,
    o_fe_flag integer,
    na_fe real,
    na_fe_spec real,
    na_fe_err real,
    na_fe_flag integer,
    mg_fe real,
    mg_fe_spec real,
    mg_fe_err real,
    mg_fe_flag integer,
    al_fe real,
    al_fe_spec real,
    al_fe_err real,
    al_fe_flag integer,
    si_fe real,
    si_fe_spec real,
    si_fe_err real,
    si_fe_flag integer,
    p_fe real,
    p_fe_spec real,
    p_fe_err real,
    p_fe_flag integer,
    s_fe real,
    s_fe_spec real,
    s_fe_err real,
    s_fe_flag integer,
    k_fe real,
    k_fe_spec real,
    k_fe_err real,
    k_fe_flag integer,
    ca_fe real,
    ca_fe_spec real,
    ca_fe_err real,
    ca_fe_flag integer,
    ti_fe real,
    ti_fe_spec real,
    ti_fe_err real,
    ti_fe_flag integer,
    tiii_fe real,
    tiii_fe_spec real,
    tiii_fe_err real,
    tiii_fe_flag integer,
    v_fe real,
    v_fe_spec real,
    v_fe_err real,
    v_fe_flag integer,
    cr_fe real,
    cr_fe_spec real,
    cr_fe_err real,
    cr_fe_flag integer,
    mn_fe real,
    mn_fe_spec real,
    mn_fe_err real,
    mn_fe_flag integer,
    fe_h real,
    fe_h_spec real,
    fe_h_err real,
    fe_h_flag integer,
    co_fe real,
    co_fe_spec real,
    co_fe_err real,
    co_fe_flag integer,
    ni_fe real,
    ni_fe_spec real,
    ni_fe_err real,
    ni_fe_flag integer,
    cu_fe real,
    cu_fe_spec real,
    cu_fe_err real,
    cu_fe_flag integer,
    ce_fe real,
    ce_fe_spec real,
    ce_fe_err real,
    ce_fe_flag integer,
    yb_fe real,
    yb_fe_spec real,
    yb_fe_err real,
    yb_fe_flag integer,
    visit_pk varchar(500),
    twomass_designation varchar(500)
);


DROP TABLE IF EXISTS dbo.dr19_catalog_to_allstar_dr17_synspec_rev1
CREATE TABLE dbo.dr19_catalog_to_allstar_dr17_synspec_rev1 (
    catalogid bigint NOT NULL,
    target_id varchar(500) NOT NULL,
    version_id smallint NOT NULL,
    distance double precision,
    best bit,
    planname_id varchar(500)
);


DROP TABLE IF EXISTS dbo.dr19_catalog_to_marvels_dr11_star
CREATE TABLE dbo.dr19_catalog_to_marvels_dr11_star (
    catalogid bigint NOT NULL,
    target_id varchar(255) NOT NULL,
    version_id smallint NOT NULL,
    distance double precision,
    best bit,
    planname_id varchar(500),
    added_by_phase smallint
);


DROP TABLE IF EXISTS dbo.dr19_catalog_to_marvels_dr12_star
CREATE TABLE dbo.dr19_catalog_to_marvels_dr12_star (
    catalogid bigint NOT NULL,
    target_id bigint NOT NULL,
    version_id smallint NOT NULL,
    distance double precision,
    best bit,
    planname_id varchar(500),
    added_by_phase smallint
);

DROP TABLE IF EXISTS dbo.dr19_marvels_dr11_star
CREATE TABLE dbo.dr19_marvels_dr11_star (
    starname varchar NOT NULL,
    twomass_name varchar,
    plate varchar,
    gsc_name varchar,
    tyc_name varchar,
    hip_name varchar,
    ra_final double precision,
    dec_final double precision,
    gsc_b double precision,
    gsc_v double precision,
    twomass_j real,
    twomass_h real,
    twomass_k real,
    sp1 varchar,
    sp2 varchar,
    rpm_log_g varchar,
    teff real,
    log_g real,
    feh real,
    gsc_b_e real,
    gsc_v_e real,
    twomass_j_e real,
    twomass_h_e real,
    twomass_k_e real,
    teff_e real,
    log_g_e real,
    feh_e real,
    epoch_0 real,
    ra_0 double precision,
    dec_0 double precision,
    ra_twomass double precision,
    dec_twomass double precision,
    gsc_pm_ra double precision,
    gsc_pm_dec double precision,
    gsc_pm_ra_e double precision,
    gsc_pm_dec_e double precision,
    tyc_b real,
    tyc_b_e real,
    tyc_v real,
    tyc_v_e real,
    hip_plx real,
    hip_plx_e real,
    hip_sptype varchar,
    twomass_designation varchar(500),
    tycho2_designation varchar(500)
);


DROP TABLE IF EXISTS dbo.dr19_marvels_dr12_star
CREATE TABLE dbo.dr19_marvels_dr12_star (
    starname varchar,
    twomass_name varchar,
    plate varchar,
    gsc_name varchar,
    tyc_name varchar,
    hip_name varchar,
    ra_final double precision,
    dec_final double precision,
    gsc_b double precision,
    gsc_v double precision,
    twomass_j real,
    twomass_h real,
    twomass_k real,
    sp1 varchar,
    sp2 varchar,
    rpm_log_g varchar,
    teff real,
    log_g real,
    feh real,
    gsc_b_e real,
    gsc_v_e real,
    twomass_j_e real,
    twomass_h_e real,
    twomass_k_e real,
    teff_e real,
    log_g_e real,
    feh_e real,
    epoch_0 real,
    ra_0 double precision,
    dec_0 double precision,
    ra_twomass double precision,
    dec_twomass double precision,
    gsc_pm_ra double precision,
    gsc_pm_dec double precision,
    gsc_pm_ra_e double precision,
    gsc_pm_dec_e double precision,
    tyc_b real,
    tyc_b_e real,
    tyc_v real,
    tyc_v_e real,
    hip_plx real,
    hip_plx_e real,
    hip_sptype varchar,
    pk bigint NOT NULL,
    twomass_designation varchar(500),
    tycho2_designation varchar(500)
);

DROP TABLE IF EXISTS dbo.dr19_catalog_to_sdss_dr16_specobj
CREATE TABLE dbo.dr19_catalog_to_sdss_dr16_specobj (
    catalogid bigint NOT NULL,
    target_id numeric(20,0) NOT NULL,
    version_id smallint NOT NULL,
    distance double precision,
    best bit
);


DROP TABLE IF EXISTS dbo.dr19_sdss_dr16_specobj
CREATE TABLE dbo.dr19_sdss_dr16_specobj (
    specobjid numeric(20,0) NOT NULL,
    bestobjid bigint,
    fluxobjid bigint,
    targetobjid bigint,
    plateid numeric(20,0),
    scienceprimary smallint,
    sdssprimary smallint,
    legacyprimary smallint,
    segueprimary smallint,
    segue1primary smallint,
    segue2primary smallint,
    bossprimary smallint,
    bossspecobjid integer,
    firstrelease varchar(32),
    survey varchar(32),
    instrument varchar(32),
    programname varchar(32),
    chunk varchar(32),
    platerun varchar(32),
    mjd integer,
    plate smallint,
    fiberid smallint,
    run1d varchar(32),
    run2d varchar(32),
    tile integer,
    designid integer,
    legacy_target1 bigint,
    legacy_target2 bigint,
    special_target1 bigint,
    special_target2 bigint,
    segue1_target1 bigint,
    segue1_target2 bigint,
    segue2_target1 bigint,
    segue2_target2 bigint,
    boss_target1 bigint,
    eboss_target0 bigint,
    eboss_target1 bigint,
    eboss_target2 bigint,
    eboss_target_id bigint,
    ancillary_target1 bigint,
    ancillary_target2 bigint,
    thing_id_targeting bigint,
    thing_id integer,
    primtarget bigint,
    sectarget bigint,
    spectrographid smallint,
    sourcetype varchar(128),
    targettype varchar(128),
    ra double precision,
    "dec" double precision,
    cx double precision,
    cy double precision,
    cz double precision,
    xfocal real,
    yfocal real,
    lambdaeff real,
    bluefiber integer,
    zoffset real,
    z real,
    zerr real,
    zwarning integer,
    class varchar(32),
    subclass varchar(32),
    rchi2 real,
    dof real,
    rchi2diff real,
    z_noqso real,
    zerr_noqso real,
    zwarning_noqso integer,
    class_noqso varchar(32),
    subclass_noqso varchar(32),
    rchi2diff_noqso real,
    z_person real,
    class_person varchar(32),
    comments_person varchar(200),
    tfile varchar(32),
    tcolumn_0 smallint,
    tcolumn_1 smallint,
    tcolumn_2 smallint,
    tcolumn_3 smallint,
    tcolumn_4 smallint,
    tcolumn_5 smallint,
    tcolumn_6 smallint,
    tcolumn_7 smallint,
    tcolumn_8 smallint,
    tcolumn_9 smallint,
    npoly real,
    theta_0 real,
    theta_1 real,
    theta_2 real,
    theta_3 real,
    theta_4 real,
    theta_5 real,
    theta_6 real,
    theta_7 real,
    theta_8 real,
    theta_9 real,
    veldisp real,
    veldisperr real,
    veldispz real,
    veldispzerr real,
    veldispchi2 real,
    veldispnpix integer,
    veldispdof integer,
    wavemin real,
    wavemax real,
    wcoverage real,
    snmedian_u real,
    snmedian_g real,
    snmedian_r real,
    snmedian_i real,
    snmedian_z real,
    snmedian real,
    chi68p real,
    fracnsigma_1 real,
    fracnsigma_2 real,
    fracnsigma_3 real,
    fracnsigma_4 real,
    fracnsigma_5 real,
    fracnsigma_6 real,
    fracnsigma_7 real,
    fracnsigma_8 real,
    fracnsigma_9 real,
    fracnsigma_10 real,
    fracnsighi_1 real,
    fracnsighi_2 real,
    fracnsighi_3 real,
    fracnsighi_4 real,
    fracnsighi_5 real,
    fracnsighi_6 real,
    fracnsighi_7 real,
    fracnsighi_8 real,
    fracnsighi_9 real,
    fracnsighi_10 real,
    fracnsiglo_1 real,
    fracnsiglo_2 real,
    fracnsiglo_3 real,
    fracnsiglo_4 real,
    fracnsiglo_5 real,
    fracnsiglo_6 real,
    fracnsiglo_7 real,
    fracnsiglo_8 real,
    fracnsiglo_9 real,
    fracnsiglo_10 real,
    spectroflux_u real,
    spectroflux_g real,
    spectroflux_r real,
    spectroflux_i real,
    spectroflux_z real,
    spectrosynflux_u real,
    spectrosynflux_g real,
    spectrosynflux_r real,
    spectrosynflux_i real,
    spectrosynflux_z real,
    spectrofluxivar_u real,
    spectrofluxivar_g real,
    spectrofluxivar_r real,
    spectrofluxivar_i real,
    spectrofluxivar_z real,
    spectrosynfluxivar_u real,
    spectrosynfluxivar_g real,
    spectrosynfluxivar_r real,
    spectrosynfluxivar_i real,
    spectrosynfluxivar_z real,
    spectroskyflux_u real,
    spectroskyflux_g real,
    spectroskyflux_r real,
    spectroskyflux_i real,
    spectroskyflux_z real,
    anyandmask integer,
    anyormask integer,
    platesn2 real,
    deredsn2 real,
    snturnoff real,
    sn1_g real,
    sn1_r real,
    sn1_i real,
    sn2_g real,
    sn2_r real,
    sn2_i real,
    elodiefilename varchar(32),
    elodieobject varchar(32),
    elodiesptype varchar(32),
    elodiebv real,
    elodieteff real,
    elodielogg real,
    elodiefeh real,
    elodiez real,
    elodiezerr real,
    elodiezmodelerr real,
    elodierchi2 real,
    elodiedof real,
    htmid bigint,
    loadversion integer
);

DROP TABLE IF EXISTS dbo.dr19_catalog_to_sdss_dr17_specobj
CREATE TABLE dbo.dr19_catalog_to_sdss_dr17_specobj (
    catalogid bigint NOT NULL,
    target_id varchar(255) NOT NULL,
    version_id smallint NOT NULL,
    distance double precision,
    best bit,
    planname_id varchar(500),
    added_by_phase smallint
);

DROP TABLE IF EXISTS dbo.dr19_catalog_to_sdss_dr17_specobj
CREATE TABLE dbo.dr19_catalog_to_sdss_dr17_specobj (
    catalogid bigint NOT NULL,
    target_id varchar(255) NOT NULL,
    version_id smallint NOT NULL,
    distance double precision,
    best bit,
    planname_id varchar(500),
    added_by_phase smallint
);

DROP TABLE IF EXISTS dbo.dr19_mangadrpall
CREATE TABLE dbo.dr19_mangadrpall (
    plate integer NOT NULL,
    ifudsgn varchar(40),
    plateifu varchar(40),
    mangaid varchar(40) NOT NULL,
    versdrp2 varchar(40),
    versdrp3 varchar(40),
    verscore varchar(40),
    versutil varchar(40),
    versprim varchar(40),
    platetyp varchar(40),
    srvymode varchar(40),
    objra double precision,
    objdec double precision,
    ifuglon double precision,
    ifuglat double precision,
    ifura double precision,
    ifudec double precision,
    ebvgal real,
    nexp integer,
    exptime real,
    drp3qual integer,
    bluesn2 real,
    redsn2 real,
    harname varchar(60),
    frlplug integer,
    cartid varchar(40),
    designid integer,
    cenra double precision,
    cendec double precision,
    airmsmin real,
    airmsmed real,
    airmsmax real,
    seemin real,
    seemed real,
    seemax real,
    transmin real,
    transmed real,
    transmax real,
    mjdmin integer,
    mjdmed integer,
    mjdmax integer,
    gfwhm real,
    rfwhm real,
    ifwhm real,
    zfwhm real,
    mngtarg1 bigint,
    mngtarg2 bigint,
    mngtarg3 bigint,
    catidnum bigint,
    plttarg varchar(40),
    manga_tileid integer,
    nsa_iauname varchar(20),
    ifutargetsize integer,
    ifudesignsize integer,
    ifudesignwrongsize integer,
    z real,
    zmin real,
    zmax real,
    szmin real,
    szmax real,
    ezmin real,
    ezmax real,
    probs real,
    pweight real,
    psweight real,
    psrweight real,
    sweight real,
    srweight real,
    eweight real,
    esweight real,
    esrweight real,
    nsa_field integer,
    nsa_run integer,
    nsa_camcol integer,
    nsa_version varchar(10),
    nsa_nsaid integer,
    nsa_nsaid_v1b integer,
    nsa_z real,
    nsa_zdist real,
    nsa_elpetro_mass real,
    nsa_elpetro_absmag_f real,
    nsa_elpetro_absmag_n real,
    nsa_elpetro_absmag_u real,
    nsa_elpetro_absmag_g real,
    nsa_elpetro_absmag_r real,
    nsa_elpetro_absmag_i real,
    nsa_elpetro_absmag_z real,
    nsa_elpetro_amivar_f real,
    nsa_elpetro_amivar_n real,
    nsa_elpetro_amivar_u real,
    nsa_elpetro_amivar_g real,
    nsa_elpetro_amivar_r real,
    nsa_elpetro_amivar_i real,
    nsa_elpetro_amivar_z real,
    nsa_elpetro_flux_f real,
    nsa_elpetro_flux_n real,
    nsa_elpetro_flux_u real,
    nsa_elpetro_flux_g real,
    nsa_elpetro_flux_r real,
    nsa_elpetro_flux_i real,
    nsa_elpetro_flux_z real,
    nsa_elpetro_flux_ivar_f real,
    nsa_elpetro_flux_ivar_n real,
    nsa_elpetro_flux_ivar_u real,
    nsa_elpetro_flux_ivar_g real,
    nsa_elpetro_flux_ivar_r real,
    nsa_elpetro_flux_ivar_i real,
    nsa_elpetro_flux_ivar_z real,
    nsa_elpetro_th50_r real,
    nsa_elpetro_phi real,
    nsa_elpetro_ba real,
    nsa_sersic_mass real,
    nsa_sersic_absmag_f real,
    nsa_sersic_absmag_n real,
    nsa_sersic_absmag_u real,
    nsa_sersic_absmag_g real,
    nsa_sersic_absmag_r real,
    nsa_sersic_absmag_i real,
    nsa_sersic_absmag_z real,
    nsa_sersic_flux_f real,
    nsa_sersic_flux_n real,
    nsa_sersic_flux_u real,
    nsa_sersic_flux_g real,
    nsa_sersic_flux_r real,
    nsa_sersic_flux_i real,
    nsa_sersic_flux_z real,
    nsa_sersic_flux_ivar_f real,
    nsa_sersic_flux_ivar_n real,
    nsa_sersic_flux_ivar_u real,
    nsa_sersic_flux_ivar_g real,
    nsa_sersic_flux_ivar_r real,
    nsa_sersic_flux_ivar_i real,
    nsa_sersic_flux_ivar_z real,
    nsa_sersic_th50 real,
    nsa_sersic_phi real,
    nsa_sersic_ba real,
    nsa_sersic_n real,
    nsa_petro_flux_f real,
    nsa_petro_flux_n real,
    nsa_petro_flux_u real,
    nsa_petro_flux_g real,
    nsa_petro_flux_r real,
    nsa_petro_flux_i real,
    nsa_petro_flux_z real,
    nsa_petro_flux_ivar_f real,
    nsa_petro_flux_ivar_n real,
    nsa_petro_flux_ivar_u real,
    nsa_petro_flux_ivar_g real,
    nsa_petro_flux_ivar_r real,
    nsa_petro_flux_ivar_i real,
    nsa_petro_flux_ivar_z real,
    nsa_petro_th50 real,
    nsa_extinction_f real,
    nsa_extinction_n real,
    nsa_extinction_u real,
    nsa_extinction_g real,
    nsa_extinction_r real,
    nsa_extinction_i real,
    nsa_extinction_z real,
    htmid bigint
);


DROP TABLE IF EXISTS dbo.dr19_mangadapall
CREATE TABLE dbo.dr19_mangadapall (
    plate integer,
    ifudesign integer,
    plateifu varchar(32),
    mangaid varchar(16),
    drpallindx integer,
    mode varchar(16),
    daptype varchar(32),
    dapdone bit(1),
    objra double precision,
    objdec double precision,
    ifura double precision,
    ifudec double precision,
    mngtarg1 integer,
    mngtarg2 integer,
    mngtarg3 integer,
    z real,
    ldist_z real,
    adist_z real,
    nsa_z real,
    nsa_zdist real,
    ldist_nsa_z real,
    adist_nsa_z real,
    nsa_elpetro_ba real,
    nsa_elpetro_phi real,
    nsa_elpetro_th50_r real,
    nsa_sersic_ba real,
    nsa_sersic_phi real,
    nsa_sersic_th50 real,
    nsa_sersic_n real,
    versdrp2 varchar(16),
    versdrp3 varchar(16),
    verscore varchar(16),
    versutil varchar(16),
    versdap varchar(16),
    drp3qual integer,
    dapqual integer,
    rdxqakey varchar(32),
    binkey varchar(32),
    sckey varchar(32),
    elmkey varchar(32),
    elfkey varchar(32),
    sikey varchar(32),
    bintype varchar(16),
    binsnr real,
    tplkey varchar(32),
    datedap varchar(12),
    dapbins integer,
    rcov90 real,
    snr_med_g real,
    snr_med_r real,
    snr_med_i real,
    snr_med_z real,
    snr_ring_g real,
    snr_ring_r real,
    snr_ring_i real,
    snr_ring_z real,
    sb_1re real,
    bin_rmax real,
    bin_r_n_05 real,
    bin_r_n_10 real,
    bin_r_n_20 real,
    bin_r_snr_05 real,
    bin_r_snr_10 real,
    bin_r_snr_20 real,
    stellar_z real,
    stellar_vel_lo real,
    stellar_vel_hi real,
    stellar_vel_lo_clip real,
    stellar_vel_hi_clip real,
    stellar_sigma_1re real,
    stellar_rchi2_1re real,
    ha_z real,
    ha_gvel_lo real,
    ha_gvel_hi real,
    ha_gvel_lo_clip real,
    ha_gvel_hi_clip real,
    ha_gsigma_1re real,
    ha_gsigma_hi real,
    ha_gsigma_hi_clip real,
    emline_rchi2_1re real,
    emline_sflux_cen_oiid_3728 real,
    emline_sflux_cen_oii_3729 real,
    emline_sflux_cen_h12_3751 real,
    emline_sflux_cen_h11_3771 real,
    emline_sflux_cen_hthe_3798 real,
    emline_sflux_cen_heta_3836 real,
    emline_sflux_cen_neiii_3869 real,
    emline_sflux_cen_hei_3889 real,
    emline_sflux_cen_hzet_3890 real,
    emline_sflux_cen_neiii_3968 real,
    emline_sflux_cen_heps_3971 real,
    emline_sflux_cen_hdel_4102 real,
    emline_sflux_cen_hgam_4341 real,
    emline_sflux_cen_heii_4687 real,
    emline_sflux_cen_hb_4862 real,
    emline_sflux_cen_oiii_4960 real,
    emline_sflux_cen_oiii_5008 real,
    emline_sflux_cen_ni_5199 real,
    emline_sflux_cen_ni_5201 real,
    emline_sflux_cen_hei_5877 real,
    emline_sflux_cen_oi_6302 real,
    emline_sflux_cen_oi_6365 real,
    emline_sflux_cen_nii_6549 real,
    emline_sflux_cen_ha_6564 real,
    emline_sflux_cen_nii_6585 real,
    emline_sflux_cen_sii_6718 real,
    emline_sflux_cen_sii_6732 real,
    emline_sflux_cen_hei_7067 real,
    emline_sflux_cen_ariii_7137 real,
    emline_sflux_cen_ariii_7753 real,
    emline_sflux_cen_peta_9017 real,
    emline_sflux_cen_siii_9071 real,
    emline_sflux_cen_pzet_9231 real,
    emline_sflux_cen_siii_9533 real,
    emline_sflux_cen_peps_9548 real,
    emline_sflux_1re_oiid_3728 real,
    emline_sflux_1re_oii_3729 real,
    emline_sflux_1re_h12_3751 real,
    emline_sflux_1re_h11_3771 real,
    emline_sflux_1re_hthe_3798 real,
    emline_sflux_1re_heta_3836 real,
    emline_sflux_1re_neiii_3869 real,
    emline_sflux_1re_hei_3889 real,
    emline_sflux_1re_hzet_3890 real,
    emline_sflux_1re_neiii_3968 real,
    emline_sflux_1re_heps_3971 real,
    emline_sflux_1re_hdel_4102 real,
    emline_sflux_1re_hgam_4341 real,
    emline_sflux_1re_heii_4687 real,
    emline_sflux_1re_hb_4862 real,
    emline_sflux_1re_oiii_4960 real,
    emline_sflux_1re_oiii_5008 real,
    emline_sflux_1re_ni_5199 real,
    emline_sflux_1re_ni_5201 real,
    emline_sflux_1re_hei_5877 real,
    emline_sflux_1re_oi_6302 real,
    emline_sflux_1re_oi_6365 real,
    emline_sflux_1re_nii_6549 real,
    emline_sflux_1re_ha_6564 real,
    emline_sflux_1re_nii_6585 real,
    emline_sflux_1re_sii_6718 real,
    emline_sflux_1re_sii_6732 real,
    emline_sflux_1re_hei_7067 real,
    emline_sflux_1re_ariii_7137 real,
    emline_sflux_1re_ariii_7753 real,
    emline_sflux_1re_peta_9017 real,
    emline_sflux_1re_siii_9071 real,
    emline_sflux_1re_pzet_9231 real,
    emline_sflux_1re_siii_9533 real,
    emline_sflux_1re_peps_9548 real,
    emline_sflux_tot_oiid_3728 real,
    emline_sflux_tot_oii_3729 real,
    emline_sflux_tot_h12_3751 real,
    emline_sflux_tot_h11_3771 real,
    emline_sflux_tot_hthe_3798 real,
    emline_sflux_tot_heta_3836 real,
    emline_sflux_tot_neiii_3869 real,
    emline_sflux_tot_hei_3889 real,
    emline_sflux_tot_hzet_3890 real,
    emline_sflux_tot_neiii_3968 real,
    emline_sflux_tot_heps_3971 real,
    emline_sflux_tot_hdel_4102 real,
    emline_sflux_tot_hgam_4341 real,
    emline_sflux_tot_heii_4687 real,
    emline_sflux_tot_hb_4862 real,
    emline_sflux_tot_oiii_4960 real,
    emline_sflux_tot_oiii_5008 real,
    emline_sflux_tot_ni_5199 real,
    emline_sflux_tot_ni_5201 real,
    emline_sflux_tot_hei_5877 real,
    emline_sflux_tot_oi_6302 real,
    emline_sflux_tot_oi_6365 real,
    emline_sflux_tot_nii_6549 real,
    emline_sflux_tot_ha_6564 real,
    emline_sflux_tot_nii_6585 real,
    emline_sflux_tot_sii_6718 real,
    emline_sflux_tot_sii_6732 real,
    emline_sflux_tot_hei_7067 real,
    emline_sflux_tot_ariii_7137 real,
    emline_sflux_tot_ariii_7753 real,
    emline_sflux_tot_peta_9017 real,
    emline_sflux_tot_siii_9071 real,
    emline_sflux_tot_pzet_9231 real,
    emline_sflux_tot_siii_9533 real,
    emline_sflux_tot_peps_9548 real,
    emline_ssb_1re_oiid_3728 real,
    emline_ssb_1re_oii_3729 real,
    emline_ssb_1re_h12_3751 real,
    emline_ssb_1re_h11_3771 real,
    emline_ssb_1re_hthe_3798 real,
    emline_ssb_1re_heta_3836 real,
    emline_ssb_1re_neiii_3869 real,
    emline_ssb_1re_hei_3889 real,
    emline_ssb_1re_hzet_3890 real,
    emline_ssb_1re_neiii_3968 real,
    emline_ssb_1re_heps_3971 real,
    emline_ssb_1re_hdel_4102 real,
    emline_ssb_1re_hgam_4341 real,
    emline_ssb_1re_heii_4687 real,
    emline_ssb_1re_hb_4862 real,
    emline_ssb_1re_oiii_4960 real,
    emline_ssb_1re_oiii_5008 real,
    emline_ssb_1re_ni_5199 real,
    emline_ssb_1re_ni_5201 real,
    emline_ssb_1re_hei_5877 real,
    emline_ssb_1re_oi_6302 real,
    emline_ssb_1re_oi_6365 real,
    emline_ssb_1re_nii_6549 real,
    emline_ssb_1re_ha_6564 real,
    emline_ssb_1re_nii_6585 real,
    emline_ssb_1re_sii_6718 real,
    emline_ssb_1re_sii_6732 real,
    emline_ssb_1re_hei_7067 real,
    emline_ssb_1re_ariii_7137 real,
    emline_ssb_1re_ariii_7753 real,
    emline_ssb_1re_peta_9017 real,
    emline_ssb_1re_siii_9071 real,
    emline_ssb_1re_pzet_9231 real,
    emline_ssb_1re_siii_9533 real,
    emline_ssb_1re_peps_9548 real,
    emline_ssb_peak_oiid_3728 real,
    emline_ssb_peak_oii_3729 real,
    emline_ssb_peak_h12_3751 real,
    emline_ssb_peak_h11_3771 real,
    emline_ssb_peak_hthe_3798 real,
    emline_ssb_peak_heta_3836 real,
    emline_ssb_peak_neiii_3869 real,
    emline_ssb_peak_hei_3889 real,
    emline_ssb_peak_hzet_3890 real,
    emline_ssb_peak_neiii_3968 real,
    emline_ssb_peak_heps_3971 real,
    emline_ssb_peak_hdel_4102 real,
    emline_ssb_peak_hgam_4341 real,
    emline_ssb_peak_heii_4687 real,
    emline_ssb_peak_hb_4862 real,
    emline_ssb_peak_oiii_4960 real,
    emline_ssb_peak_oiii_5008 real,
    emline_ssb_peak_ni_5199 real,
    emline_ssb_peak_ni_5201 real,
    emline_ssb_peak_hei_5877 real,
    emline_ssb_peak_oi_6302 real,
    emline_ssb_peak_oi_6365 real,
    emline_ssb_peak_nii_6549 real,
    emline_ssb_peak_ha_6564 real,
    emline_ssb_peak_nii_6585 real,
    emline_ssb_peak_sii_6718 real,
    emline_ssb_peak_sii_6732 real,
    emline_ssb_peak_hei_7067 real,
    emline_ssb_peak_ariii_7137 real,
    emline_ssb_peak_ariii_7753 real,
    emline_ssb_peak_peta_9017 real,
    emline_ssb_peak_siii_9071 real,
    emline_ssb_peak_pzet_9231 real,
    emline_ssb_peak_siii_9533 real,
    emline_ssb_peak_peps_9548 real,
    emline_sew_1re_oiid_3728 real,
    emline_sew_1re_oii_3729 real,
    emline_sew_1re_h12_3751 real,
    emline_sew_1re_h11_3771 real,
    emline_sew_1re_hthe_3798 real,
    emline_sew_1re_heta_3836 real,
    emline_sew_1re_neiii_3869 real,
    emline_sew_1re_hei_3889 real,
    emline_sew_1re_hzet_3890 real,
    emline_sew_1re_neiii_3968 real,
    emline_sew_1re_heps_3971 real,
    emline_sew_1re_hdel_4102 real,
    emline_sew_1re_hgam_4341 real,
    emline_sew_1re_heii_4687 real,
    emline_sew_1re_hb_4862 real,
    emline_sew_1re_oiii_4960 real,
    emline_sew_1re_oiii_5008 real,
    emline_sew_1re_ni_5199 real,
    emline_sew_1re_ni_5201 real,
    emline_sew_1re_hei_5877 real,
    emline_sew_1re_oi_6302 real,
    emline_sew_1re_oi_6365 real,
    emline_sew_1re_nii_6549 real,
    emline_sew_1re_ha_6564 real,
    emline_sew_1re_nii_6585 real,
    emline_sew_1re_sii_6718 real,
    emline_sew_1re_sii_6732 real,
    emline_sew_1re_hei_7067 real,
    emline_sew_1re_ariii_7137 real,
    emline_sew_1re_ariii_7753 real,
    emline_sew_1re_peta_9017 real,
    emline_sew_1re_siii_9071 real,
    emline_sew_1re_pzet_9231 real,
    emline_sew_1re_siii_9533 real,
    emline_sew_1re_peps_9548 real,
    emline_sew_peak_oiid_3728 real,
    emline_sew_peak_oii_3729 real,
    emline_sew_peak_h12_3751 real,
    emline_sew_peak_h11_3771 real,
    emline_sew_peak_hthe_3798 real,
    emline_sew_peak_heta_3836 real,
    emline_sew_peak_neiii_3869 real,
    emline_sew_peak_hei_3889 real,
    emline_sew_peak_hzet_3890 real,
    emline_sew_peak_neiii_3968 real,
    emline_sew_peak_heps_3971 real,
    emline_sew_peak_hdel_4102 real,
    emline_sew_peak_hgam_4341 real,
    emline_sew_peak_heii_4687 real,
    emline_sew_peak_hb_4862 real,
    emline_sew_peak_oiii_4960 real,
    emline_sew_peak_oiii_5008 real,
    emline_sew_peak_ni_5199 real,
    emline_sew_peak_ni_5201 real,
    emline_sew_peak_hei_5877 real,
    emline_sew_peak_oi_6302 real,
    emline_sew_peak_oi_6365 real,
    emline_sew_peak_nii_6549 real,
    emline_sew_peak_ha_6564 real,
    emline_sew_peak_nii_6585 real,
    emline_sew_peak_sii_6718 real,
    emline_sew_peak_sii_6732 real,
    emline_sew_peak_hei_7067 real,
    emline_sew_peak_ariii_7137 real,
    emline_sew_peak_ariii_7753 real,
    emline_sew_peak_peta_9017 real,
    emline_sew_peak_siii_9071 real,
    emline_sew_peak_pzet_9231 real,
    emline_sew_peak_siii_9533 real,
    emline_sew_peak_peps_9548 real,
    emline_gflux_cen_oii_3727 real,
    emline_gflux_cen_oii_3729 real,
    emline_gflux_cen_h12_3751 real,
    emline_gflux_cen_h11_3771 real,
    emline_gflux_cen_hthe_3798 real,
    emline_gflux_cen_heta_3836 real,
    emline_gflux_cen_neiii_3869 real,
    emline_gflux_cen_hei_3889 real,
    emline_gflux_cen_hzet_3890 real,
    emline_gflux_cen_neiii_3968 real,
    emline_gflux_cen_heps_3971 real,
    emline_gflux_cen_hdel_4102 real,
    emline_gflux_cen_hgam_4341 real,
    emline_gflux_cen_heii_4687 real,
    emline_gflux_cen_hb_4862 real,
    emline_gflux_cen_oiii_4960 real,
    emline_gflux_cen_oiii_5008 real,
    emline_gflux_cen_ni_5199 real,
    emline_gflux_cen_ni_5201 real,
    emline_gflux_cen_hei_5877 real,
    emline_gflux_cen_oi_6302 real,
    emline_gflux_cen_oi_6365 real,
    emline_gflux_cen_nii_6549 real,
    emline_gflux_cen_ha_6564 real,
    emline_gflux_cen_nii_6585 real,
    emline_gflux_cen_sii_6718 real,
    emline_gflux_cen_sii_6732 real,
    emline_gflux_cen_hei_7067 real,
    emline_gflux_cen_ariii_7137 real,
    emline_gflux_cen_ariii_7753 real,
    emline_gflux_cen_peta_9017 real,
    emline_gflux_cen_siii_9071 real,
    emline_gflux_cen_pzet_9231 real,
    emline_gflux_cen_siii_9533 real,
    emline_gflux_cen_peps_9548 real,
    emline_gflux_1re_oii_3727 real,
    emline_gflux_1re_oii_3729 real,
    emline_gflux_1re_h12_3751 real,
    emline_gflux_1re_h11_3771 real,
    emline_gflux_1re_hthe_3798 real,
    emline_gflux_1re_heta_3836 real,
    emline_gflux_1re_neiii_3869 real,
    emline_gflux_1re_hei_3889 real,
    emline_gflux_1re_hzet_3890 real,
    emline_gflux_1re_neiii_3968 real,
    emline_gflux_1re_heps_3971 real,
    emline_gflux_1re_hdel_4102 real,
    emline_gflux_1re_hgam_4341 real,
    emline_gflux_1re_heii_4687 real,
    emline_gflux_1re_hb_4862 real,
    emline_gflux_1re_oiii_4960 real,
    emline_gflux_1re_oiii_5008 real,
    emline_gflux_1re_ni_5199 real,
    emline_gflux_1re_ni_5201 real,
    emline_gflux_1re_hei_5877 real,
    emline_gflux_1re_oi_6302 real,
    emline_gflux_1re_oi_6365 real,
    emline_gflux_1re_nii_6549 real,
    emline_gflux_1re_ha_6564 real,
    emline_gflux_1re_nii_6585 real,
    emline_gflux_1re_sii_6718 real,
    emline_gflux_1re_sii_6732 real,
    emline_gflux_1re_hei_7067 real,
    emline_gflux_1re_ariii_7137 real,
    emline_gflux_1re_ariii_7753 real,
    emline_gflux_1re_peta_9017 real,
    emline_gflux_1re_siii_9071 real,
    emline_gflux_1re_pzet_9231 real,
    emline_gflux_1re_siii_9533 real,
    emline_gflux_1re_peps_9548 real,
    emline_gflux_tot_oii_3727 real,
    emline_gflux_tot_oii_3729 real,
    emline_gflux_tot_h12_3751 real,
    emline_gflux_tot_h11_3771 real,
    emline_gflux_tot_hthe_3798 real,
    emline_gflux_tot_heta_3836 real,
    emline_gflux_tot_neiii_3869 real,
    emline_gflux_tot_hei_3889 real,
    emline_gflux_tot_hzet_3890 real,
    emline_gflux_tot_neiii_3968 real,
    emline_gflux_tot_heps_3971 real,
    emline_gflux_tot_hdel_4102 real,
    emline_gflux_tot_hgam_4341 real,
    emline_gflux_tot_heii_4687 real,
    emline_gflux_tot_hb_4862 real,
    emline_gflux_tot_oiii_4960 real,
    emline_gflux_tot_oiii_5008 real,
    emline_gflux_tot_ni_5199 real,
    emline_gflux_tot_ni_5201 real,
    emline_gflux_tot_hei_5877 real,
    emline_gflux_tot_oi_6302 real,
    emline_gflux_tot_oi_6365 real,
    emline_gflux_tot_nii_6549 real,
    emline_gflux_tot_ha_6564 real,
    emline_gflux_tot_nii_6585 real,
    emline_gflux_tot_sii_6718 real,
    emline_gflux_tot_sii_6732 real,
    emline_gflux_tot_hei_7067 real,
    emline_gflux_tot_ariii_7137 real,
    emline_gflux_tot_ariii_7753 real,
    emline_gflux_tot_peta_9017 real,
    emline_gflux_tot_siii_9071 real,
    emline_gflux_tot_pzet_9231 real,
    emline_gflux_tot_siii_9533 real,
    emline_gflux_tot_peps_9548 real,
    emline_gsb_1re_oii_3727 real,
    emline_gsb_1re_oii_3729 real,
    emline_gsb_1re_h12_3751 real,
    emline_gsb_1re_h11_3771 real,
    emline_gsb_1re_hthe_3798 real,
    emline_gsb_1re_heta_3836 real,
    emline_gsb_1re_neiii_3869 real,
    emline_gsb_1re_hei_3889 real,
    emline_gsb_1re_hzet_3890 real,
    emline_gsb_1re_neiii_3968 real,
    emline_gsb_1re_heps_3971 real,
    emline_gsb_1re_hdel_4102 real,
    emline_gsb_1re_hgam_4341 real,
    emline_gsb_1re_heii_4687 real,
    emline_gsb_1re_hb_4862 real,
    emline_gsb_1re_oiii_4960 real,
    emline_gsb_1re_oiii_5008 real,
    emline_gsb_1re_ni_5199 real,
    emline_gsb_1re_ni_5201 real,
    emline_gsb_1re_hei_5877 real,
    emline_gsb_1re_oi_6302 real,
    emline_gsb_1re_oi_6365 real,
    emline_gsb_1re_nii_6549 real,
    emline_gsb_1re_ha_6564 real,
    emline_gsb_1re_nii_6585 real,
    emline_gsb_1re_sii_6718 real,
    emline_gsb_1re_sii_6732 real,
    emline_gsb_1re_hei_7067 real,
    emline_gsb_1re_ariii_7137 real,
    emline_gsb_1re_ariii_7753 real,
    emline_gsb_1re_peta_9017 real,
    emline_gsb_1re_siii_9071 real,
    emline_gsb_1re_pzet_9231 real,
    emline_gsb_1re_siii_9533 real,
    emline_gsb_1re_peps_9548 real,
    emline_gsb_peak_oii_3727 real,
    emline_gsb_peak_oii_3729 real,
    emline_gsb_peak_h12_3751 real,
    emline_gsb_peak_h11_3771 real,
    emline_gsb_peak_hthe_3798 real,
    emline_gsb_peak_heta_3836 real,
    emline_gsb_peak_neiii_3869 real,
    emline_gsb_peak_hei_3889 real,
    emline_gsb_peak_hzet_3890 real,
    emline_gsb_peak_neiii_3968 real,
    emline_gsb_peak_heps_3971 real,
    emline_gsb_peak_hdel_4102 real,
    emline_gsb_peak_hgam_4341 real,
    emline_gsb_peak_heii_4687 real,
    emline_gsb_peak_hb_4862 real,
    emline_gsb_peak_oiii_4960 real,
    emline_gsb_peak_oiii_5008 real,
    emline_gsb_peak_ni_5199 real,
    emline_gsb_peak_ni_5201 real,
    emline_gsb_peak_hei_5877 real,
    emline_gsb_peak_oi_6302 real,
    emline_gsb_peak_oi_6365 real,
    emline_gsb_peak_nii_6549 real,
    emline_gsb_peak_ha_6564 real,
    emline_gsb_peak_nii_6585 real,
    emline_gsb_peak_sii_6718 real,
    emline_gsb_peak_sii_6732 real,
    emline_gsb_peak_hei_7067 real,
    emline_gsb_peak_ariii_7137 real,
    emline_gsb_peak_ariii_7753 real,
    emline_gsb_peak_peta_9017 real,
    emline_gsb_peak_siii_9071 real,
    emline_gsb_peak_pzet_9231 real,
    emline_gsb_peak_siii_9533 real,
    emline_gsb_peak_peps_9548 real,
    emline_gew_1re_oii_3727 real,
    emline_gew_1re_oii_3729 real,
    emline_gew_1re_h12_3751 real,
    emline_gew_1re_h11_3771 real,
    emline_gew_1re_hthe_3798 real,
    emline_gew_1re_heta_3836 real,
    emline_gew_1re_neiii_3869 real,
    emline_gew_1re_hei_3889 real,
    emline_gew_1re_hzet_3890 real,
    emline_gew_1re_neiii_3968 real,
    emline_gew_1re_heps_3971 real,
    emline_gew_1re_hdel_4102 real,
    emline_gew_1re_hgam_4341 real,
    emline_gew_1re_heii_4687 real,
    emline_gew_1re_hb_4862 real,
    emline_gew_1re_oiii_4960 real,
    emline_gew_1re_oiii_5008 real,
    emline_gew_1re_ni_5199 real,
    emline_gew_1re_ni_5201 real,
    emline_gew_1re_hei_5877 real,
    emline_gew_1re_oi_6302 real,
    emline_gew_1re_oi_6365 real,
    emline_gew_1re_nii_6549 real,
    emline_gew_1re_ha_6564 real,
    emline_gew_1re_nii_6585 real,
    emline_gew_1re_sii_6718 real,
    emline_gew_1re_sii_6732 real,
    emline_gew_1re_hei_7067 real,
    emline_gew_1re_ariii_7137 real,
    emline_gew_1re_ariii_7753 real,
    emline_gew_1re_peta_9017 real,
    emline_gew_1re_siii_9071 real,
    emline_gew_1re_pzet_9231 real,
    emline_gew_1re_siii_9533 real,
    emline_gew_1re_peps_9548 real,
    emline_gew_peak_oii_3727 real,
    emline_gew_peak_oii_3729 real,
    emline_gew_peak_h12_3751 real,
    emline_gew_peak_h11_3771 real,
    emline_gew_peak_hthe_3798 real,
    emline_gew_peak_heta_3836 real,
    emline_gew_peak_neiii_3869 real,
    emline_gew_peak_hei_3889 real,
    emline_gew_peak_hzet_3890 real,
    emline_gew_peak_neiii_3968 real,
    emline_gew_peak_heps_3971 real,
    emline_gew_peak_hdel_4102 real,
    emline_gew_peak_hgam_4341 real,
    emline_gew_peak_heii_4687 real,
    emline_gew_peak_hb_4862 real,
    emline_gew_peak_oiii_4960 real,
    emline_gew_peak_oiii_5008 real,
    emline_gew_peak_ni_5199 real,
    emline_gew_peak_ni_5201 real,
    emline_gew_peak_hei_5877 real,
    emline_gew_peak_oi_6302 real,
    emline_gew_peak_oi_6365 real,
    emline_gew_peak_nii_6549 real,
    emline_gew_peak_ha_6564 real,
    emline_gew_peak_nii_6585 real,
    emline_gew_peak_sii_6718 real,
    emline_gew_peak_sii_6732 real,
    emline_gew_peak_hei_7067 real,
    emline_gew_peak_ariii_7137 real,
    emline_gew_peak_ariii_7753 real,
    emline_gew_peak_peta_9017 real,
    emline_gew_peak_siii_9071 real,
    emline_gew_peak_pzet_9231 real,
    emline_gew_peak_siii_9533 real,
    emline_gew_peak_peps_9548 real,
    specindex_lo_cn1 real,
    specindex_lo_cn2 real,
    specindex_lo_ca4227 real,
    specindex_lo_g4300 real,
    specindex_lo_fe4383 real,
    specindex_lo_ca4455 real,
    specindex_lo_fe4531 real,
    specindex_lo_c24668 real,
    specindex_lo_hb real,
    specindex_lo_fe5015 real,
    specindex_lo_mg1 real,
    specindex_lo_mg2 real,
    specindex_lo_mgb real,
    specindex_lo_fe5270 real,
    specindex_lo_fe5335 real,
    specindex_lo_fe5406 real,
    specindex_lo_fe5709 real,
    specindex_lo_fe5782 real,
    specindex_lo_nad real,
    specindex_lo_tio1 real,
    specindex_lo_tio2 real,
    specindex_lo_hdeltaa real,
    specindex_lo_hgammaa real,
    specindex_lo_hdeltaf real,
    specindex_lo_hgammaf real,
    specindex_lo_cahk real,
    specindex_lo_caii1 real,
    specindex_lo_caii2 real,
    specindex_lo_caii3 real,
    specindex_lo_pa17 real,
    specindex_lo_pa14 real,
    specindex_lo_pa12 real,
    specindex_lo_mgicvd real,
    specindex_lo_naicvd real,
    specindex_lo_mgiir real,
    specindex_lo_fehcvd real,
    specindex_lo_nai real,
    specindex_lo_btio real,
    specindex_lo_atio real,
    specindex_lo_cah1 real,
    specindex_lo_cah2 real,
    specindex_lo_naisdss real,
    specindex_lo_tio2sdss real,
    specindex_lo_d4000 real,
    specindex_lo_dn4000 real,
    specindex_lo_tiocvd real,
    specindex_hi_cn1 real,
    specindex_hi_cn2 real,
    specindex_hi_ca4227 real,
    specindex_hi_g4300 real,
    specindex_hi_fe4383 real,
    specindex_hi_ca4455 real,
    specindex_hi_fe4531 real,
    specindex_hi_c24668 real,
    specindex_hi_hb real,
    specindex_hi_fe5015 real,
    specindex_hi_mg1 real,
    specindex_hi_mg2 real,
    specindex_hi_mgb real,
    specindex_hi_fe5270 real,
    specindex_hi_fe5335 real,
    specindex_hi_fe5406 real,
    specindex_hi_fe5709 real,
    specindex_hi_fe5782 real,
    specindex_hi_nad real,
    specindex_hi_tio1 real,
    specindex_hi_tio2 real,
    specindex_hi_hdeltaa real,
    specindex_hi_hgammaa real,
    specindex_hi_hdeltaf real,
    specindex_hi_hgammaf real,
    specindex_hi_cahk real,
    specindex_hi_caii1 real,
    specindex_hi_caii2 real,
    specindex_hi_caii3 real,
    specindex_hi_pa17 real,
    specindex_hi_pa14 real,
    specindex_hi_pa12 real,
    specindex_hi_mgicvd real,
    specindex_hi_naicvd real,
    specindex_hi_mgiir real,
    specindex_hi_fehcvd real,
    specindex_hi_nai real,
    specindex_hi_btio real,
    specindex_hi_atio real,
    specindex_hi_cah1 real,
    specindex_hi_cah2 real,
    specindex_hi_naisdss real,
    specindex_hi_tio2sdss real,
    specindex_hi_d4000 real,
    specindex_hi_dn4000 real,
    specindex_hi_tiocvd real,
    specindex_lo_clip_cn1 real,
    specindex_lo_clip_cn2 real,
    specindex_lo_clip_ca4227 real,
    specindex_lo_clip_g4300 real,
    specindex_lo_clip_fe4383 real,
    specindex_lo_clip_ca4455 real,
    specindex_lo_clip_fe4531 real,
    specindex_lo_clip_c24668 real,
    specindex_lo_clip_hb real,
    specindex_lo_clip_fe5015 real,
    specindex_lo_clip_mg1 real,
    specindex_lo_clip_mg2 real,
    specindex_lo_clip_mgb real,
    specindex_lo_clip_fe5270 real,
    specindex_lo_clip_fe5335 real,
    specindex_lo_clip_fe5406 real,
    specindex_lo_clip_fe5709 real,
    specindex_lo_clip_fe5782 real,
    specindex_lo_clip_nad real,
    specindex_lo_clip_tio1 real,
    specindex_lo_clip_tio2 real,
    specindex_lo_clip_hdeltaa real,
    specindex_lo_clip_hgammaa real,
    specindex_lo_clip_hdeltaf real,
    specindex_lo_clip_hgammaf real,
    specindex_lo_clip_cahk real,
    specindex_lo_clip_caii1 real,
    specindex_lo_clip_caii2 real,
    specindex_lo_clip_caii3 real,
    specindex_lo_clip_pa17 real,
    specindex_lo_clip_pa14 real,
    specindex_lo_clip_pa12 real,
    specindex_lo_clip_mgicvd real,
    specindex_lo_clip_naicvd real,
    specindex_lo_clip_mgiir real,
    specindex_lo_clip_fehcvd real,
    specindex_lo_clip_nai real,
    specindex_lo_clip_btio real,
    specindex_lo_clip_atio real,
    specindex_lo_clip_cah1 real,
    specindex_lo_clip_cah2 real,
    specindex_lo_clip_naisdss real,
    specindex_lo_clip_tio2sdss real,
    specindex_lo_clip_d4000 real,
    specindex_lo_clip_dn4000 real,
    specindex_lo_clip_tiocvd real,
    specindex_hi_clip_cn1 real,
    specindex_hi_clip_cn2 real,
    specindex_hi_clip_ca4227 real,
    specindex_hi_clip_g4300 real,
    specindex_hi_clip_fe4383 real,
    specindex_hi_clip_ca4455 real,
    specindex_hi_clip_fe4531 real,
    specindex_hi_clip_c24668 real,
    specindex_hi_clip_hb real,
    specindex_hi_clip_fe5015 real,
    specindex_hi_clip_mg1 real,
    specindex_hi_clip_mg2 real,
    specindex_hi_clip_mgb real,
    specindex_hi_clip_fe5270 real,
    specindex_hi_clip_fe5335 real,
    specindex_hi_clip_fe5406 real,
    specindex_hi_clip_fe5709 real,
    specindex_hi_clip_fe5782 real,
    specindex_hi_clip_nad real,
    specindex_hi_clip_tio1 real,
    specindex_hi_clip_tio2 real,
    specindex_hi_clip_hdeltaa real,
    specindex_hi_clip_hgammaa real,
    specindex_hi_clip_hdeltaf real,
    specindex_hi_clip_hgammaf real,
    specindex_hi_clip_cahk real,
    specindex_hi_clip_caii1 real,
    specindex_hi_clip_caii2 real,
    specindex_hi_clip_caii3 real,
    specindex_hi_clip_pa17 real,
    specindex_hi_clip_pa14 real,
    specindex_hi_clip_pa12 real,
    specindex_hi_clip_mgicvd real,
    specindex_hi_clip_naicvd real,
    specindex_hi_clip_mgiir real,
    specindex_hi_clip_fehcvd real,
    specindex_hi_clip_nai real,
    specindex_hi_clip_btio real,
    specindex_hi_clip_atio real,
    specindex_hi_clip_cah1 real,
    specindex_hi_clip_cah2 real,
    specindex_hi_clip_naisdss real,
    specindex_hi_clip_tio2sdss real,
    specindex_hi_clip_d4000 real,
    specindex_hi_clip_dn4000 real,
    specindex_hi_clip_tiocvd real,
    specindex_1re_cn1 real,
    specindex_1re_cn2 real,
    specindex_1re_ca4227 real,
    specindex_1re_g4300 real,
    specindex_1re_fe4383 real,
    specindex_1re_ca4455 real,
    specindex_1re_fe4531 real,
    specindex_1re_c24668 real,
    specindex_1re_hb real,
    specindex_1re_fe5015 real,
    specindex_1re_mg1 real,
    specindex_1re_mg2 real,
    specindex_1re_mgb real,
    specindex_1re_fe5270 real,
    specindex_1re_fe5335 real,
    specindex_1re_fe5406 real,
    specindex_1re_fe5709 real,
    specindex_1re_fe5782 real,
    specindex_1re_nad real,
    specindex_1re_tio1 real,
    specindex_1re_tio2 real,
    specindex_1re_hdeltaa real,
    specindex_1re_hgammaa real,
    specindex_1re_hdeltaf real,
    specindex_1re_hgammaf real,
    specindex_1re_cahk real,
    specindex_1re_caii1 real,
    specindex_1re_caii2 real,
    specindex_1re_caii3 real,
    specindex_1re_pa17 real,
    specindex_1re_pa14 real,
    specindex_1re_pa12 real,
    specindex_1re_mgicvd real,
    specindex_1re_naicvd real,
    specindex_1re_mgiir real,
    specindex_1re_fehcvd real,
    specindex_1re_nai real,
    specindex_1re_btio real,
    specindex_1re_atio real,
    specindex_1re_cah1 real,
    specindex_1re_cah2 real,
    specindex_1re_naisdss real,
    specindex_1re_tio2sdss real,
    specindex_1re_d4000 real,
    specindex_1re_dn4000 real,
    specindex_1re_tiocvd real,
    sfr_1re real,
    sfr_tot real,
    htmid bigint,
    pk bigint NOT NULL
);



