USE [minidb2]
GO

/****** Object:  Table [dbo].[allstar_dr17_test2]    Script Date: 1/24/2025 12:08:32 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[allstar_dr17_test2](
	[file] [nvarchar](50) NOT NULL,
	[apogee_id] [nvarchar](50) NOT NULL,
	[target_id] [nvarchar](50) NOT NULL,
	[apstar_id] [nvarchar](50) NOT NULL,
	[aspcap_id] [nvarchar](100) NOT NULL,
	[telescope] [nvarchar](50) NOT NULL,
	[location_id] [tinyint] NOT NULL,
	[field] [nvarchar](50) NOT NULL,
	[alt_id] [nvarchar](50) NOT NULL,
	[ra] [float] NOT NULL,
	[dec] [float] NOT NULL,
	[glon] [float] NOT NULL,
	[glat] [float] NOT NULL,
	[j] [float] NOT NULL,
	[j_err] [tinyint] NOT NULL,
	[h] [float] NOT NULL,
	[h_err] [tinyint] NOT NULL,
	[k] [float] NOT NULL,
	[k_err] [tinyint] NOT NULL,
	[src_h] [nvarchar](1) NULL,
	[wash_m] [tinyint] NOT NULL,
	[wash_m_err] [tinyint] NOT NULL,
	[wash_t2] [tinyint] NOT NULL,
	[wash_t2_err] [tinyint] NOT NULL,
	[ddo51] [tinyint] NOT NULL,
	[ddo51_err] [tinyint] NOT NULL,
	[irac_3_6] [tinyint] NOT NULL,
	[irac_3_6_err] [tinyint] NOT NULL,
	[irac_4_5] [tinyint] NOT NULL,
	[irac_4_5_err] [tinyint] NOT NULL,
	[irac_5_8] [tinyint] NOT NULL,
	[irac_5_8_err] [tinyint] NOT NULL,
	[irac_8_0] [tinyint] NOT NULL,
	[irac_8_0_err] [tinyint] NOT NULL,
	[wise_4_5] [tinyint] NOT NULL,
	[wise_4_5_err] [tinyint] NOT NULL,
	[targ_4_5] [tinyint] NOT NULL,
	[targ_4_5_err] [tinyint] NOT NULL,
	[wash_ddo51_giant_flag] [tinyint] NOT NULL,
	[wash_ddo51_star_flag] [tinyint] NOT NULL,
	[targ_pmra] [tinyint] NOT NULL,
	[targ_pmdec] [tinyint] NOT NULL,
	[targ_pm_src] [nvarchar](1) NULL,
	[ak_targ] [nvarchar](1) NULL,
	[ak_targ_method] [nvarchar](1) NULL,
	[ak_wise] [nvarchar](1) NULL,
	[sfd_ebv] [nvarchar](1) NULL,
	[apogee_target1] [tinyint] NOT NULL,
	[apogee_target2] [int] NOT NULL,
	[apogee2_target1] [tinyint] NOT NULL,
	[apogee2_target2] [int] NOT NULL,
	[apogee2_target3] [tinyint] NOT NULL,
	[apogee2_target4] [tinyint] NOT NULL,
	[targflags] [nvarchar](50) NOT NULL,
	[survey] [nvarchar](50) NOT NULL,
	[programname] [nvarchar](1) NULL,
	[nvisits] [tinyint] NOT NULL,
	[snr] [float] NOT NULL,
	[snrev] [float] NOT NULL,
	[starflag] [date] NOT NULL,
	[starflags] [nvarchar](50) NOT NULL,
	[andflag] [date] NOT NULL,
	[andflags] [nvarchar](50) NOT NULL,
	[vhelio_avg] [float] NOT NULL,
	[vscatter] [tinyint] NOT NULL,
	[verr] [float] NOT NULL,
	[rv_teff] [float] NOT NULL,
	[rv_logg] [float] NOT NULL,
	[rv_feh] [float] NOT NULL,
	[rv_alpha] [tinyint] NOT NULL,
	[rv_carb] [tinyint] NOT NULL,
	[rv_chi2] [float] NOT NULL,
	[rv_ccfwhm] [float] NOT NULL,
	[rv_autofwhm] [float] NOT NULL,
	[rv_flag] [tinyint] NOT NULL,
	[n_components] [tinyint] NOT NULL,
	[meanfib] [tinyint] NOT NULL,
	[sigfib] [tinyint] NOT NULL,
	[min_h] [float] NOT NULL,
	[max_h] [float] NOT NULL,
	[min_jk] [float] NOT NULL,
	[max_jk] [float] NOT NULL,
	[gaiaedr3_source_id] [bigint] NOT NULL,
	[gaiaedr3_parallax] [float] NOT NULL,
	[gaiaedr3_parallax_error] [float] NOT NULL,
	[gaiaedr3_pmra] [float] NOT NULL,
	[gaiaedr3_pmra_error] [float] NOT NULL,
	[gaiaedr3_pmdec] [float] NOT NULL,
	[gaiaedr3_pmdec_error] [float] NOT NULL,
	[gaiaedr3_phot_g_mean_mag] [float] NOT NULL,
	[gaiaedr3_phot_bp_mean_mag] [float] NOT NULL,
	[gaiaedr3_phot_rp_mean_mag] [float] NOT NULL,
	[gaiaedr3_dr2_radial_velocity] [nvarchar](1) NULL,
	[gaiaedr3_dr2_radial_velocity_error] [nvarchar](1) NULL,
	[gaiaedr3_r_med_geo] [float] NOT NULL,
	[gaiaedr3_r_lo_geo] [float] NOT NULL,
	[gaiaedr3_r_hi_geo] [float] NOT NULL,
	[gaiaedr3_r_med_photogeo] [float] NOT NULL,
	[gaiaedr3_r_lo_photogeo] [float] NOT NULL,
	[gaiaedr3_r_hi_photogeo] [float] NOT NULL,
	[aspcap_grid] [nvarchar](50) NOT NULL,
	[fparam_grid] [nvarchar](1000) NOT NULL,
	[chi2_grid] [nvarchar](150) NOT NULL,
	[fparam] [nvarchar](50) NOT NULL,
	[fparam_cov] [nvarchar](300) NOT NULL,
	[aspcap_chi2] [float] NOT NULL,
	[param] [nvarchar](50) NOT NULL,
	[param_cov] [nvarchar](500) NOT NULL,
	[paramflag] [nvarchar](50) NOT NULL,
	[aspcapflag] [int] NOT NULL,
	[aspcapflags] [nvarchar](50) NOT NULL,
	[frac_badpix] [float] NOT NULL,
	[frac_lowsnr] [float] NOT NULL,
	[frac_sigsky] [float] NOT NULL,
	[felem] [nvarchar](150) NOT NULL,
	[felem_err] [nvarchar](350) NOT NULL,
	[x_h] [nvarchar](150) NOT NULL,
	[x_h_err] [nvarchar](300) NOT NULL,
	[x_m] [nvarchar](150) NOT NULL,
	[x_m_err] [nvarchar](300) NOT NULL,
	[elem_chi2] [nvarchar](300) NOT NULL,
	[elemfrac] [nvarchar](150) NOT NULL,
	[elemflag] [nvarchar](100) NOT NULL,
	[extratarg] [tinyint] NOT NULL,
	[memberflag] [tinyint] NOT NULL,
	[member] [nvarchar](1) NULL,
	[x_h_spec] [nvarchar](150) NOT NULL,
	[x_m_spec] [nvarchar](150) NOT NULL,
	[teff] [float] NOT NULL,
	[teff_err] [float] NOT NULL,
	[logg] [float] NOT NULL,
	[logg_err] [float] NOT NULL,
	[m_h] [nvarchar](1) NULL,
	[m_h_err] [nvarchar](1) NULL,
	[alpha_m] [nvarchar](1) NULL,
	[alpha_m_err] [nvarchar](1) NULL,
	[vmicro] [tinyint] NOT NULL,
	[vmacro] [tinyint] NOT NULL,
	[vsini] [float] NOT NULL,
	[teff_spec] [smallint] NOT NULL,
	[logg_spec] [float] NOT NULL,
	[c_fe] [nvarchar](1) NULL,
	[c_fe_spec] [nvarchar](1) NULL,
	[c_fe_err] [nvarchar](1) NULL,
	[c_fe_flag] [tinyint] NOT NULL,
	[ci_fe] [nvarchar](1) NULL,
	[ci_fe_spec] [nvarchar](1) NULL,
	[ci_fe_err] [nvarchar](1) NULL,
	[ci_fe_flag] [tinyint] NOT NULL,
	[n_fe] [nvarchar](1) NULL,
	[n_fe_spec] [nvarchar](1) NULL,
	[n_fe_err] [nvarchar](1) NULL,
	[n_fe_flag] [tinyint] NOT NULL,
	[o_fe] [nvarchar](1) NULL,
	[o_fe_spec] [nvarchar](1) NULL,
	[o_fe_err] [nvarchar](1) NULL,
	[o_fe_flag] [tinyint] NOT NULL,
	[na_fe] [nvarchar](1) NULL,
	[na_fe_spec] [nvarchar](1) NULL,
	[na_fe_err] [nvarchar](1) NULL,
	[na_fe_flag] [tinyint] NOT NULL,
	[mg_fe] [nvarchar](1) NULL,
	[mg_fe_spec] [nvarchar](1) NULL,
	[mg_fe_err] [nvarchar](1) NULL,
	[mg_fe_flag] [tinyint] NOT NULL,
	[al_fe] [nvarchar](1) NULL,
	[al_fe_spec] [nvarchar](1) NULL,
	[al_fe_err] [nvarchar](1) NULL,
	[al_fe_flag] [smallint] NOT NULL,
	[si_fe] [nvarchar](1) NULL,
	[si_fe_spec] [nvarchar](1) NULL,
	[si_fe_err] [nvarchar](1) NULL,
	[si_fe_flag] [tinyint] NOT NULL,
	[p_fe] [nvarchar](1) NULL,
	[p_fe_spec] [nvarchar](1) NULL,
	[p_fe_err] [nvarchar](1) NULL,
	[p_fe_flag] [tinyint] NOT NULL,
	[s_fe] [nvarchar](1) NULL,
	[s_fe_spec] [nvarchar](1) NULL,
	[s_fe_err] [nvarchar](1) NULL,
	[s_fe_flag] [tinyint] NOT NULL,
	[k_fe] [nvarchar](1) NULL,
	[k_fe_spec] [nvarchar](1) NULL,
	[k_fe_err] [nvarchar](1) NULL,
	[k_fe_flag] [smallint] NOT NULL,
	[ca_fe] [nvarchar](1) NULL,
	[ca_fe_spec] [nvarchar](1) NULL,
	[ca_fe_err] [nvarchar](1) NULL,
	[ca_fe_flag] [tinyint] NOT NULL,
	[ti_fe] [nvarchar](1) NULL,
	[ti_fe_spec] [nvarchar](1) NULL,
	[ti_fe_err] [nvarchar](1) NULL,
	[ti_fe_flag] [tinyint] NOT NULL,
	[tiii_fe] [nvarchar](1) NULL,
	[tiii_fe_spec] [nvarchar](1) NULL,
	[tiii_fe_err] [nvarchar](1) NULL,
	[tiii_fe_flag] [tinyint] NOT NULL,
	[v_fe] [nvarchar](1) NULL,
	[v_fe_spec] [nvarchar](1) NULL,
	[v_fe_err] [nvarchar](1) NULL,
	[v_fe_flag] [smallint] NOT NULL,
	[cr_fe] [nvarchar](1) NULL,
	[cr_fe_spec] [nvarchar](1) NULL,
	[cr_fe_err] [nvarchar](1) NULL,
	[cr_fe_flag] [tinyint] NOT NULL,
	[mn_fe] [nvarchar](1) NULL,
	[mn_fe_spec] [nvarchar](1) NULL,
	[mn_fe_err] [nvarchar](1) NULL,
	[mn_fe_flag] [tinyint] NOT NULL,
	[fe_h] [nvarchar](1) NULL,
	[fe_h_spec] [nvarchar](1) NULL,
	[fe_h_err] [nvarchar](1) NULL,
	[fe_h_flag] [tinyint] NOT NULL,
	[co_fe] [nvarchar](1) NULL,
	[co_fe_spec] [nvarchar](1) NULL,
	[co_fe_err] [nvarchar](1) NULL,
	[co_fe_flag] [smallint] NOT NULL,
	[ni_fe] [nvarchar](1) NULL,
	[ni_fe_spec] [nvarchar](1) NULL,
	[ni_fe_err] [nvarchar](1) NULL,
	[ni_fe_flag] [tinyint] NOT NULL,
	[cu_fe] [nvarchar](1) NULL,
	[cu_fe_spec] [nvarchar](1) NULL,
	[cu_fe_err] [nvarchar](1) NULL,
	[cu_fe_flag] [smallint] NOT NULL,
	[ce_fe] [nvarchar](1) NULL,
	[ce_fe_spec] [nvarchar](1) NULL,
	[ce_fe_err] [nvarchar](1) NULL,
	[ce_fe_flag] [smallint] NOT NULL,
	[yb_fe] [nvarchar](1) NULL,
	[yb_fe_spec] [nvarchar](1) NULL,
	[yb_fe_err] [nvarchar](1) NULL,
	[yb_fe_flag] [tinyint] NOT NULL,
	[visit_pk] [nvarchar](1200) NOT NULL,
	[twomass_designation] [nvarchar](50) NOT NULL
) ON [PRIMARY]
GO


