

--ALTER DATABASE BestDR13_CCI
--ADD FILEGROUP SPEC

ALTER DATABASE BestDR13_CCI
ADD FILE (
	NAME = 'SPEC_01',
	FILENAME = 'D:\sql_db\BestDR13_CCI\SPEC_01.ndf',
	SIZE = 20GB,
	MAXSIZE = unlimited,
	FILEGROWTH = 100MB
) TO FILEGROUP SPEC

ALTER DATABASE BestDR13_CCI
ADD FILE (
	NAME = 'SPEC_02',
	FILENAME = 'D:\sql_db\BestDR13_CCI\SPEC_02.ndf',
	SIZE = 20GB,
	MAXSIZE = unlimited,
	FILEGROWTH = 100MB
) TO FILEGROUP SPEC

ALTER DATABASE BestDR13_CCI
ADD FILE (
	NAME = 'SPEC_03',
	FILENAME = 'D:\sql_db\BestDR13_CCI\SPEC_03.ndf',
	SIZE = 20GB,
	MAXSIZE = unlimited,
	FILEGROWTH = 100MB
) TO FILEGROUP SPEC

ALTER DATABASE BestDR13_CCI
ADD FILE (
	NAME = 'SPEC_04',
	FILENAME = 'D:\sql_db\BestDR13_CCI\SPEC_04.ndf',
	SIZE = 20GB,
	MAXSIZE = unlimited,
	FILEGROWTH = 100MB
) TO FILEGROUP SPEC

ALTER DATABASE BestDR13_CCI
ADD FILE (
	NAME = 'SPEC_05',
	FILENAME = 'D:\sql_db\BestDR13_CCI\SPEC_05.ndf',
	SIZE = 20GB,
	MAXSIZE = unlimited,
	FILEGROWTH = 100MB
) TO FILEGROUP SPEC

ALTER DATABASE BestDR13_CCI
ADD FILE (
	NAME = 'SPEC_06',
	FILENAME = 'D:\sql_db\BestDR13_CCI\SPEC_06.ndf',
	SIZE = 20GB,
	MAXSIZE = unlimited,
	FILEGROWTH = 100MB
) TO FILEGROUP SPEC

ALTER DATABASE BestDR13_CCI
ADD FILE (
	NAME = 'SPEC_07',
	FILENAME = 'D:\sql_db\BestDR13_CCI\SPEC_07.ndf',
	SIZE = 20GB,
	MAXSIZE = unlimited,
	FILEGROWTH = 100MB
) TO FILEGROUP SPEC

ALTER DATABASE BestDR13_CCI
ADD FILE (
	NAME = 'SPEC_08',
	FILENAME = 'D:\sql_db\BestDR13_CCI\SPEC_08.ndf',
	SIZE = 20GB,
	MAXSIZE = unlimited,
	FILEGROWTH = 100MB
) TO FILEGROUP SPEC

ALTER DATABASE BestDR13_CCI
ADD FILE (
	NAME = 'SPEC_09',
	FILENAME = 'D:\sql_db\BestDR13_CCI\SPEC_09.ndf',
	SIZE = 20GB,
	MAXSIZE = unlimited,
	FILEGROWTH = 100MB
) TO FILEGROUP SPEC

ALTER DATABASE BestDR13_CCI
ADD FILE (
	NAME = 'SPEC_10',
	FILENAME = 'D:\sql_db\BestDR13_CCI\SPEC_10.ndf',
	SIZE = 20GB,
	MAXSIZE = unlimited,
	FILEGROWTH = 100MB
) TO FILEGROUP SPEC



