bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1035-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1043-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1045-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1140-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1231-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1239-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1241-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1331-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1332-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1336-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1339-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1345-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1350-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1356-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1359-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1402-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1412-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1450-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1453-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1458-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1462-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1478-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1659-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1729-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1737-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1739-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1740-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1741-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1749-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1869-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1889-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1891-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1893-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1895-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1896-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1897-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1904-42.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1907-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-1992-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2074-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2075-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2076-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2078-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2125-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2126-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2131-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2134-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2137-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2141-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2188-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2189-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2190-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2206-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2207-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2243-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2247-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2248-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2259-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2298-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2299-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2304-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2305-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2326-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2327-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2328-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2333-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2334-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2335-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2379-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2391-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2392-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2566-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2574-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2576-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2582-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2583-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2659-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2662-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2735-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2738-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2740-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2777-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2821-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2822-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2825-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2826-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2830-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2831-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2863-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2864-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2883-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2887-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2888-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2961-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2964-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2986-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2987-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-2989-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3015-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3031-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3059-42.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3103-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3130-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3177-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3180-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3183-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3184-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3185-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3187-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3225-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3226-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3325-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3358-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3388-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3462-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3478-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3513-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3518-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3525-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3530-42.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3538-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3560-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3562-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3605-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3606-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3630-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3631-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3635-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3644-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3647-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3650-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3664-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3698-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3699-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3704-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3705-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3712-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3716-42.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3723-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3804-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3805-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3813-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3818-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3830-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3836-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3838-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3840-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3841-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3842-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3893-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3894-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3900-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3903-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3905-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3909-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3910-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3918-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3919-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3926-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3927-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3958-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3964-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3965-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3970-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3971-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3972-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3992-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3996-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-3997-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4002-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4003-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4007-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4010-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4011-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4134-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4135-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4144-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4152-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4204-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4208-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4233-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4264-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4294-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4335-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4344-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4380-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4381-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4382-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4392-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4469-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4470-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4504-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4508-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4512-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4517-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4518-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4520-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4550-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4552-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4569-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4570-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4571-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4576-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4588-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4599-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4600-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4623-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4628-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4632-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4633-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4646-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4649-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4670-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4671-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4674-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4678-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4679-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4682-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4682-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4800-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4828-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4828-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4829-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4832-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4832-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4836-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4836-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4843-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4844-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4851-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4879-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4880-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-4887-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5037-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5038-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5044-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5045-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5060-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5061-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5065-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5066-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5071-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5079-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5080-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5087-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5112-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5115-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5116-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5125-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5137-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5138-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5140-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5182-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5183-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5194-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5224-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5225-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5237-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5308-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5312-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5313-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5314-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5317-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5318-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5322-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5323-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5326-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5327-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5330-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5360-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5362-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5375-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5378-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5381-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5384-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5385-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5387-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5390-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5396-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5401-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5402-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5403-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5408-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5409-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5415-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5416-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5421-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5598-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5636-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5640-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5641-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5655-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5656-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5714-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5794-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5814-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5815-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5817-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5824-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5849-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5933-41.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5934-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5935-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5959-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5960-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5972-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5973-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5976-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5982-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-5999-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6003-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6004-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6005-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6074-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6075-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6103-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6104-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6105-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6118-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6121-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6122-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6123-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6160-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6161-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6162-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6166-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6169-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6174-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6176-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6177-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6182-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6354-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6361-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6366-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6371-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6372-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6413-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6475-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6485-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6505-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6509-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6514-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6519-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6572-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6573-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6574-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6581-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6585-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6591-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6597-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6605-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6708-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6709-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6727-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6749-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6753-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6781-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6793-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-6850-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-7178-648.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-7243-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-7264-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-7265-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-745-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-752-40.csv -T -c -t"," >> bcplog.txt
bcp BestDR7.dbo.UberAstro in \\blue1\sdss-csv\csv\ubercsv\uberastro-756-44.csv -T -c -t"," >> bcplog.txt
