"""
Generate SQL to reload 4 SPEC-filegroup tables from BESTTEST into BestDR20.
Strategy: DROP → CREATE TABLE ON SPEC → CREATE CLUSTERED INDEX WITH PAGE COMPRESSION → INSERT SELECT.
"""

import pymssql

TABLES = {
    'spAll':       'specObjID',
    'allspec':     'allspec_id',
    'multiplex':   'multiplex_id',
    'mwm_targets': 'PK',
}

OUTPUT = r'H:\GitHub\sqlloader\dr20\load_spec_tables.sql'


def col_type(row):
    dt = row['DATA_TYPE']
    if dt in ('varchar', 'nvarchar', 'char', 'nchar', 'varbinary', 'binary'):
        n = row['CHARACTER_MAXIMUM_LENGTH']
        return f"{dt}(max)" if n == -1 else f"{dt}({n})"
    elif dt in ('decimal', 'numeric'):
        return f"{dt}({row['NUMERIC_PRECISION']},{row['NUMERIC_SCALE']})"
    elif dt == 'float':
        p = row['NUMERIC_PRECISION']
        return f"float({p})" if p and p != 53 else 'float'
    elif dt in ('datetime2', 'time', 'datetimeoffset'):
        p = row['DATETIME_PRECISION']
        return f"{dt}({p})" if p is not None else dt
    else:
        return dt


def main():
    conn = pymssql.connect(server='localhost', database='BESTTEST')
    cur = conn.cursor(as_dict=True)

    lines = [
        '-- Generated by gen_spec_load.py',
        '-- Reloads 4 SPEC tables from BESTTEST into BestDR20',
        '-- DROP > CREATE TABLE ON SPEC > CI WITH PAGE COMPRESSION > INSERT',
        'USE BestDR20;',
        'GO',
        '',
    ]

    for table, pk_col in TABLES.items():
        print(f"Processing {table} (PK: {pk_col})...")

        cur.execute("""
            SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH,
                   NUMERIC_PRECISION, NUMERIC_SCALE, DATETIME_PRECISION, IS_NULLABLE
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = %s
            ORDER BY ORDINAL_POSITION
        """, (table,))
        cols = cur.fetchall()

        if not cols:
            print(f"  WARNING: no columns found for {table}, skipping")
            continue

        lines += [
            f'-- ============================================================',
            f'-- {table}',
            f'-- ============================================================',
            f'IF OBJECT_ID(\'dbo.{table}\') IS NOT NULL DROP TABLE dbo.{table};',
            f'GO',
            f'',
            f'CREATE TABLE dbo.{table} (',
        ]

        col_defs = []
        for c in cols:
            null = 'NULL' if c['IS_NULLABLE'] == 'YES' else 'NOT NULL'
            col_defs.append(f"    [{c['COLUMN_NAME']}] {col_type(c)} {null}")
        lines.append(',\n'.join(col_defs))
        lines += [
            f') ON [SPEC];',
            f'GO',
            f'',
            f'CREATE CLUSTERED INDEX [pk_{table}_{pk_col}] ON dbo.{table} ([{pk_col}])',
            f'    WITH (DATA_COMPRESSION = PAGE) ON [SPEC];',
            f'GO',
            f'',
            f'INSERT INTO dbo.{table} WITH (TABLOCK)',
            f'SELECT * FROM BESTTEST.dbo.{table};',
            f'GO',
            f'',
            f'SELECT \'{table}: \' + CAST(COUNT(*) AS varchar) + \' rows loaded\' FROM dbo.{table};',
            f'GO',
            f'',
        ]

        cur.execute("SELECT SUM(row_count) AS row_count FROM sys.dm_db_partition_stats WHERE object_id = OBJECT_ID(%s) AND index_id < 2", (table,))
        r = cur.fetchone()
        rows = r['row_count'] if r else '?'
        print(f"  {len(cols)} columns, ~{rows} rows")

    conn.close()

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"\nWritten to {OUTPUT}")


if __name__ == '__main__':
    main()
