"""
Generate SQL to load VAC/astra tables from BESTTEST into BestDR20.
Strategy: DROP (if exists) > CREATE TABLE ON [filegroup] > CREATE CLUSTERED INDEX WITH PAGE COMPRESSION > INSERT SELECT.
PK column and filegroup are sourced from BestDR20.dbo.IndexMap (code='K').
Only tables with a matching IndexMap entry are included.

Tables NOT processed here (no IndexMap entry): spall_epoch, spall_allepoch, lvm_drpall, lvm_dapall
Tables in IndexMap but loaded via CSV (not BESTTEST): minesweeper
"""

import pymssql

TABLES = [
    'boss_net_boss_star',
    'boss_net_boss_visit',
    'corv_boss_visit',
    'line_forest_boss_star',
    'line_forest_boss_visit',
    'm_dwarf_type_boss_star',
    'm_dwarf_type_boss_visit',
    'slam_boss_star',
    'snow_white_boss_star',
    'mwm_boss_allstar',
    'mwm_boss_allvisit',
]

OUTPUT = r'H:\GitHub\sqlloader\dr20\load_vac_tables.sql'


def col_type(row):
    dt = row['DATA_TYPE']
    if dt in ('varchar', 'nvarchar', 'char', 'nchar', 'varbinary', 'binary'):
        n = row['CHARACTER_MAXIMUM_LENGTH']
        return f"{dt}(max)" if n == -1 else f"{dt}({n})"
    elif dt in ('decimal', 'numeric'):
        return f"{dt}({row['NUMERIC_PRECISION']},{row['NUMERIC_SCALE']})"
    elif dt == 'float':
        p = row['NUMERIC_PRECISION']
        return f"float({p})" if p and p != 53 else 'float'
    elif dt in ('datetime2', 'time', 'datetimeoffset'):
        p = row['DATETIME_PRECISION']
        return f"{dt}({p})" if p is not None else dt
    else:
        return dt


def get_indexmap_pks(tables):
    """Query BestDR20.IndexMap for PK definitions. Returns {tableName: (fieldList, filegroup)}."""
    conn = pymssql.connect(server='localhost', database='BestDR20')
    cur = conn.cursor(as_dict=True)
    placeholders = ', '.join(['%s'] * len(tables))
    cur.execute(
        f"SELECT tableName, fieldList, filegroup FROM dbo.IndexMap "
        f"WHERE code = 'K' AND tableName IN ({placeholders})",
        tables,
    )
    result = {r['tableName']: (r['fieldList'].strip(), r['filegroup'].strip()) for r in cur.fetchall()}
    conn.close()
    return result


def main():
    pk_map = get_indexmap_pks(TABLES)
    print(f"IndexMap: found PKs for {len(pk_map)} of {len(TABLES)} tables")
    for t, (col, fg) in sorted(pk_map.items()):
        print(f"  {t}: CI={col}, filegroup={fg}")

    conn = pymssql.connect(server='localhost', database='BESTTEST')
    cur = conn.cursor(as_dict=True)

    lines = [
        '-- Generated by gen_vac_load.py',
        f'-- Loads VAC/astra tables from BESTTEST into BestDR20',
        '-- PK column and filegroup sourced from BestDR20.dbo.IndexMap',
        '-- DROP > CREATE TABLE ON [filegroup] > CI WITH PAGE COMPRESSION > INSERT SELECT',
        'USE BestDR20;',
        'GO',
        '',
    ]

    skipped = []

    for table in TABLES:
        if table not in pk_map:
            print(f"  SKIPPED {table}: no entry in IndexMap")
            skipped.append(table)
            continue

        pk_col, filegroup = pk_map[table]
        print(f"Processing {table} (CI={pk_col}, fg={filegroup})...")

        cur.execute("""
            SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH,
                   NUMERIC_PRECISION, NUMERIC_SCALE, DATETIME_PRECISION, IS_NULLABLE
            FROM INFORMATION_SCHEMA.COLUMNS
            WHERE TABLE_NAME = %s
            ORDER BY ORDINAL_POSITION
        """, (table,))
        cols = cur.fetchall()

        if not cols:
            print(f"  WARNING: no columns found in BESTTEST for {table}, skipping")
            skipped.append(table)
            continue

        cur.execute("""
            SELECT SUM(row_count) AS row_count
            FROM sys.dm_db_partition_stats
            WHERE object_id = OBJECT_ID(%s) AND index_id < 2
        """, (table,))
        r = cur.fetchone()
        rows = r['row_count'] if r else '?'
        print(f"  {len(cols)} columns, ~{rows} rows in BESTTEST")

        lines += [
            f'-- ============================================================',
            f'-- {table}  (CI: {pk_col}, filegroup: {filegroup})',
            f'-- ============================================================',
            f"IF OBJECT_ID('dbo.{table}') IS NOT NULL DROP TABLE dbo.{table};",
            f'GO',
            f'',
            f'CREATE TABLE dbo.{table} (',
        ]

        col_defs = []
        for c in cols:
            null = 'NULL' if c['IS_NULLABLE'] == 'YES' else 'NOT NULL'
            col_defs.append(f"    [{c['COLUMN_NAME']}] {col_type(c)} {null}")
        lines.append(',\n'.join(col_defs))
        lines += [
            f') ON [{filegroup}];',
            f'GO',
            f'',
            f'CREATE CLUSTERED INDEX [ci_{table}_{pk_col}] ON dbo.{table} ([{pk_col}])',
            f'    WITH (DATA_COMPRESSION = PAGE) ON [{filegroup}];',
            f'GO',
            f'',
            f'INSERT INTO dbo.{table} WITH (TABLOCK)',
            f'SELECT * FROM BESTTEST.dbo.{table};',
            f'GO',
            f'',
            f"SELECT '{table}: ' + CAST(COUNT(*) AS varchar) + ' rows loaded' FROM dbo.{table};",
            f'GO',
            f'',
        ]

    conn.close()

    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))

    print(f"\nWritten to {OUTPUT}")
    if skipped:
        print(f"\nSkipped (not in IndexMap):")
        for t in skipped:
            print(f"  {t}")


if __name__ == '__main__':
    main()
