-- Generated by gen_vac_load.py
-- Loads 14 VAC/astra tables from BESTTEST into BestDR20 on SPEC filegroup
-- DROP > CREATE TABLE ON [SPEC] > CI WITH PAGE COMPRESSION > INSERT SELECT
USE BestDR20;
GO
