-- Recreate the 2 tables with varchar(max) for array columns
-- dr20_allstar_dr17_synspec_rev1 and dr20_gaia_dr3_nss_two_body_orbit

USE minidb_dr20;
GO

-- Table 1: dr20_allstar_dr17_synspec_rev1
EXEC sp_executesql N'
DROP TABLE IF EXISTS dbo.dr20_allstar_dr17_synspec_rev1;
';
GO

EXEC sp_executesql N'
DROP TABLE IF EXISTS dbo.dr20_gaia_dr3_nss_two_body_orbit;
';
GO

PRINT 'Tables dropped. Now recreating with varchar(max) for array columns...';
GO
DROP TABLE IF EXISTS dbo.dr20_allstar_dr17_synspec_rev1
CREATE TABLE dbo.dr20_allstar_dr17_synspec_rev1 (
    [file] varchar(max),
    apogee_id varchar(max),
    target_id varchar(max),
    apstar_id varchar(max) NOT NULL,
    aspcap_id varchar(max),
    telescope varchar(max),
    location_id integer,
    field varchar(max),
    alt_id varchar(max),
    ra double precision,
    [dec] double precision,
    glon double precision,
    glat double precision,
    j real,
    j_err real,
    h real,
    h_err real,
    k real,
    k_err real,
    src_h varchar(max),
    wash_m real,
    wash_m_err real,
    wash_t2 real,
    wash_t2_err real,
    ddo51 real,
    ddo51_err real,
    irac_3_6 real,
    irac_3_6_err real,
    irac_4_5 real,
    irac_4_5_err real,
    irac_5_8 real,
    irac_5_8_err real,
    irac_8_0 real,
    irac_8_0_err real,
    wise_4_5 real,
    wise_4_5_err real,
    targ_4_5 real,
    targ_4_5_err real,
    wash_ddo51_giant_flag integer,
    wash_ddo51_star_flag integer,
    targ_pmra real,
    targ_pmdec real,
    targ_pm_src varchar(max),
    ak_targ real,
    ak_targ_method varchar(max),
    ak_wise real,
    sfd_ebv real,
    apogee_target1 integer,
    apogee_target2 integer,
    apogee2_target1 integer,
    apogee2_target2 integer,
    apogee2_target3 integer,
    apogee2_target4 integer,
    targflags varchar(max),
    survey varchar(max),
    programname varchar(max),
    nvisits integer,
    snr real,
    snrev real,
    starflag bigint,
    starflags varchar(max),
    andflag bigint,
    andflags varchar(max),
    vhelio_avg real,
    vscatter real,
    verr real,
    rv_teff real,
    rv_logg real,
    rv_feh real,
    rv_alpha real,
    rv_carb real,
    rv_chi2 real,
    rv_ccfwhm real,
    rv_autofwhm real,
    rv_flag integer,
    n_components integer,
    meanfib real,
    sigfib real,
    min_h real,
    max_h real,
    min_jk real,
    max_jk real,
    gaiaedr3_source_id bigint,
    gaiaedr3_parallax real,
    gaiaedr3_parallax_error real,
    gaiaedr3_pmra real,
    gaiaedr3_pmra_error real,
    gaiaedr3_pmdec real,
    gaiaedr3_pmdec_error real,
    gaiaedr3_phot_g_mean_mag real,
    gaiaedr3_phot_bp_mean_mag real,
    gaiaedr3_phot_rp_mean_mag real,
    gaiaedr3_dr2_radial_velocity real,
    gaiaedr3_dr2_radial_velocity_error real,
    gaiaedr3_r_med_geo real,
    gaiaedr3_r_lo_geo real,
    gaiaedr3_r_hi_geo real,
    gaiaedr3_r_med_photogeo real,
    gaiaedr3_r_lo_photogeo real,
    gaiaedr3_r_hi_photogeo real,
    aspcap_grid varchar(max),
    fparam_grid varchar(max),
    chi2_grid varchar(max),
    fparam varchar(max),
    fparam_cov varchar(max),
    aspcap_chi2 real,
    param varchar(max),
    param_cov varchar(max),
    paramflag varchar(max),
    aspcapflag bigint,
    aspcapflags varchar(max),
    frac_badpix real,
    frac_lowsnr real,
    frac_sigsky real,
    felem varchar(max),
    felem_err varchar(max),
    x_h varchar(max),
    x_h_err varchar(max),
    x_m varchar(max),
    x_m_err varchar(max),
    elem_chi2 varchar(max),
    elemfrac varchar(max),
    elemflag varchar(max),
    extratarg integer,
    memberflag bigint,
    member varchar(max),
    x_h_spec varchar(max),
    x_m_spec varchar(max),
    teff real,
    teff_err real,
    logg real,
    logg_err real,
    m_h real,
    m_h_err real,
    alpha_m real,
    alpha_m_err real,
    vmicro real,
    vmacro real,
    vsini real,
    teff_spec real,
    logg_spec real,
    c_fe real,
    c_fe_spec real,
    c_fe_err real,
    c_fe_flag integer,
    ci_fe real,
    ci_fe_spec real,
    ci_fe_err real,
    ci_fe_flag integer,
    n_fe real,
    n_fe_spec real,
    n_fe_err real,
    n_fe_flag integer,
    o_fe real,
    o_fe_spec real,
    o_fe_err real,
    o_fe_flag integer,
    na_fe real,
    na_fe_spec real,
    na_fe_err real,
    na_fe_flag integer,
    mg_fe real,
    mg_fe_spec real,
    mg_fe_err real,
    mg_fe_flag integer,
    al_fe real,
    al_fe_spec real,
    al_fe_err real,
    al_fe_flag integer,
    si_fe real,
    si_fe_spec real,
    si_fe_err real,
    si_fe_flag integer,
    p_fe real,
    p_fe_spec real,
    p_fe_err real,
    p_fe_flag integer,
    s_fe real,
    s_fe_spec real,
    s_fe_err real,
    s_fe_flag integer,
    k_fe real,
    k_fe_spec real,
    k_fe_err real,
    k_fe_flag integer,
    ca_fe real,
    ca_fe_spec real,
    ca_fe_err real,
    ca_fe_flag integer,
    ti_fe real,
    ti_fe_spec real,
    ti_fe_err real,
    ti_fe_flag integer,
    tiii_fe real,
    tiii_fe_spec real,
    tiii_fe_err real,
    tiii_fe_flag integer,
    v_fe real,
    v_fe_spec real,
    v_fe_err real,
    v_fe_flag integer,
    cr_fe real,
    cr_fe_spec real,
    cr_fe_err real,
    cr_fe_flag integer,
    mn_fe real,
    mn_fe_spec real,
    mn_fe_err real,
    mn_fe_flag integer,
    fe_h real,
    fe_h_spec real,
    fe_h_err real,
    fe_h_flag integer,
    co_fe real,
    co_fe_spec real,
    co_fe_err real,
    co_fe_flag integer,
    ni_fe real,
    ni_fe_spec real,
    ni_fe_err real,
    ni_fe_flag integer,
    cu_fe real,
    cu_fe_spec real,
    cu_fe_err real,
    cu_fe_flag integer,
    ce_fe real,
    ce_fe_spec real,
    ce_fe_err real,
    ce_fe_flag integer,
    yb_fe real,
    yb_fe_spec real,
    yb_fe_err real,
    yb_fe_flag integer,
    visit_pk varchar(max),
    twomass_designation varchar(max)
);

GO

DROP TABLE IF EXISTS dbo.dr20_gaia_dr3_nss_two_body_orbit
CREATE TABLE dbo.dr20_gaia_dr3_nss_two_body_orbit (
    solution_id bigint,
    source_id bigint NOT NULL,
    nss_solution_type varchar(max),
    ra double precision,
    ra_error real,
    [dec] double precision,
    dec_error real,
    parallax double precision,
    parallax_error real,
    pmra double precision,
    pmra_error real,
    pmdec double precision,
    pmdec_error real,
    a_thiele_innes double precision,
    a_thiele_innes_error real,
    b_thiele_innes double precision,
    b_thiele_innes_error real,
    f_thiele_innes double precision,
    f_thiele_innes_error real,
    g_thiele_innes double precision,
    g_thiele_innes_error real,
    c_thiele_innes double precision,
    c_thiele_innes_error real,
    h_thiele_innes double precision,
    h_thiele_innes_error real,
    period double precision,
    period_error real,
    t_periastron double precision,
    t_periastron_error real,
    eccentricity double precision,
    eccentricity_error real,
    center_of_mass_velocity double precision,
    center_of_mass_velocity_error real,
    semi_amplitude_primary double precision,
    semi_amplitude_primary_error real,
    semi_amplitude_secondary double precision,
    semi_amplitude_secondary_error real,
    mass_ratio double precision,
    mass_ratio_error real,
    fill_factor_primary double precision,
    fill_factor_primary_error real,
    fill_factor_secondary double precision,
    fill_factor_secondary_error real,
    inclination double precision,
    inclination_error real,
    arg_periastron double precision,
    arg_periastron_error real,
    temperature_ratio double precision,
    temperature_ratio_error real,
    temperature_ratio_definition smallint,
    astrometric_n_obs_al integer,
    astrometric_n_good_obs_al integer,
    rv_n_obs_primary integer,
    rv_n_good_obs_primary integer,
    rv_n_obs_secondary integer,
    rv_n_good_obs_secondary integer,
    phot_g_n_obs integer,
    phot_g_n_good_obs integer,
    bit_index bigint,
    corr_vec varchar(max),
    obj_func real,
    goodness_of_fit real,
    efficiency real,
    significance real,
    flags bigint,
    conf_spectro_period real,
    r_pole_sum double precision,
    r_l1_point_sum double precision,
    r_spher_sum double precision,
    ecl_time_primary double precision,
    ecl_time_secondary double precision,
    ecl_dur_primary double precision,
    ecl_dur_secondary double precision,
    g_luminosity_ratio double precision,
    input_period_error real,
    g_rank double precision,
    astrometric_jitter double precision
);
GO
