
-----------------------------------------------
-------------clustered and insert--------------
-----------------------------------------------
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; ALTER TABLE apogeeDesign ADD CONSTRAINT pk_apogeeDesign_designid PRIMARY KEY CLUSTERED (designid)  WITH (DATA_COMPRESSION = page) ON [SPEC]
 
insert [BestDR16].[dbo].[apogeeDesign] with (tablock)  select * from [BESTTEST].[dbo].[apogeeDesign] 
 
 
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; ALTER TABLE apogeeField ADD CONSTRAINT pk_apogeeField_location_id PRIMARY KEY CLUSTERED (location_id)  WITH (DATA_COMPRESSION = page) ON [SPEC]
 
insert [BestDR16].[dbo].[apogeeField] with (tablock)  select * from [BESTTEST].[dbo].[apogeeField] 
 
 
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; ALTER TABLE apogeeObject ADD CONSTRAINT pk_apogeeObject_target_id PRIMARY KEY CLUSTERED (target_id)  WITH (DATA_COMPRESSION = page) ON [SPEC]
 
insert [BestDR16].[dbo].[apogeeObject] with (tablock)  select * from [BESTTEST].[dbo].[apogeeObject] 
 
 
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; ALTER TABLE apogeePlate ADD CONSTRAINT pk_apogeePlate_plate_visit_id PRIMARY KEY CLUSTERED (plate_visit_id)  WITH (DATA_COMPRESSION = page) ON [SPEC]
 
insert [BestDR16].[dbo].[apogeePlate] with (tablock)  select * from [BESTTEST].[dbo].[apogeePlate] 
 
 
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; ALTER TABLE apogeeStar ADD CONSTRAINT pk_apogeeStar_apstar_id PRIMARY KEY CLUSTERED (apstar_id)  WITH (DATA_COMPRESSION = page) ON [SPEC]
 
insert [BestDR16].[dbo].[apogeeStar] with (tablock)  select * from [BESTTEST].[dbo].[apogeeStar] 
 
 
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; ALTER TABLE apogeeStarAllVisit ADD CONSTRAINT pk_apogeeStarAllVisit_visit_id_a PRIMARY KEY CLUSTERED (visit_id,apstar_id)  WITH (DATA_COMPRESSION = page) ON [SPEC]
 
insert [BestDR16].[dbo].[apogeeStarAllVisit] with (tablock)  select * from [BESTTEST].[dbo].[apogeeStarAllVisit] 
 
 
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; ALTER TABLE apogeeStarVisit ADD CONSTRAINT pk_apogeeStarVisit_visit_id PRIMARY KEY CLUSTERED (visit_id)  WITH (DATA_COMPRESSION = page) ON [SPEC]
 
insert [BestDR16].[dbo].[apogeeStarVisit] with (tablock)  select * from [BESTTEST].[dbo].[apogeeStarVisit] 
 
 
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; ALTER TABLE apogeeVisit ADD CONSTRAINT pk_apogeeVisit_visit_id PRIMARY KEY CLUSTERED (visit_id)  WITH (DATA_COMPRESSION = page) ON [SPEC]
 
insert [BestDR16].[dbo].[apogeeVisit] with (tablock)  select * from [BESTTEST].[dbo].[apogeeVisit] 
 
 
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; ALTER TABLE aspcapStar ADD CONSTRAINT pk_aspcapStar_aspcap_id PRIMARY KEY CLUSTERED (aspcap_id)  WITH (DATA_COMPRESSION = page) ON [SPEC]
 
insert [BestDR16].[dbo].[aspcapStar] with (tablock)  select * from [BESTTEST].[dbo].[aspcapStar] 
 
 
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; ALTER TABLE aspcapStarCovar ADD CONSTRAINT pk_aspcapStarCovar_aspcap_covar_ PRIMARY KEY CLUSTERED (aspcap_covar_id,aspcap_id)  WITH (DATA_COMPRESSION = page) ON [SPEC]
 
insert [BestDR16].[dbo].[aspcapStarCovar] with (tablock)  select * from [BESTTEST].[dbo].[aspcapStarCovar] 
 
 
-----------------------------------------------
--------------- non clustered -----------------
-----------------------------------------------
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; CREATE INDEX i_apogeeObject_apogee_id_j_h_k_j ON apogeeObject(apogee_id,j,h,k,j_err,h_err,k_err) WITH (SORT_IN_TEMPDB=ON ,DATA_COMPRESSION = page) ON [SPEC]
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; CREATE INDEX i_apogeeStar_apogee_id ON apogeeStar(apogee_id) WITH (SORT_IN_TEMPDB=ON ,DATA_COMPRESSION = page) ON [SPEC]
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; CREATE INDEX i_apogeeStar_htmID ON apogeeStar(htmID) WITH (SORT_IN_TEMPDB=ON ,DATA_COMPRESSION = page) ON [SPEC]
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; CREATE INDEX i_apogeeVisit_apogee_id ON apogeeVisit(apogee_id) WITH (SORT_IN_TEMPDB=ON ,DATA_COMPRESSION = page) ON [SPEC]
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; CREATE INDEX i_apogeeVisit_plate_mjd_fiberid ON apogeeVisit(plate,mjd,fiberid) WITH (SORT_IN_TEMPDB=ON ,DATA_COMPRESSION = page) ON [SPEC]
SET ANSI_NULLS ON; SET ANSI_PADDING ON; SET ANSI_WARNINGS ON; SET ARITHABORT OFF; SET CONCAT_NULL_YIELDS_NULL ON;  SET NUMERIC_ROUNDABORT OFF; SET QUOTED_IDENTIFIER ON; CREATE INDEX i_aspcapStar_apstar_id ON aspcapStar(apstar_id) WITH (SORT_IN_TEMPDB=ON ,DATA_COMPRESSION = page) ON [SPEC]
