	DROP TABLE apogee_net_apogee_star
	DROP TABLE aspcap_apogee_star
	DROP TABLE astro_nn_apogee_star
	DROP TABLE astro_nn_apogee_visit
	DROP TABLE astro_nn_dist_apogee_star
	DROP TABLE boss_net_boss_star
	DROP TABLE boss_net_boss_visit
	DROP TABLE corv_boss_visit
	DROP TABLE line_forest_boss_star
	DROP TABLE line_forest_boss_visit
	DROP TABLE lite_all_star
	DROP TABLE m_dwarf_type_boss_star
	DROP TABLE m_dwarf_type_boss_visit
	DROP TABLE mwm_apogee_allstar
	DROP TABLE mwm_apogee_allvisit
	DROP TABLE mwm_boss_allstar
	DROP TABLE mwm_boss_allvisit
	DROP TABLE mwm_targets
	DROP TABLE slam_boss_star
	DROP TABLE snow_white_boss_star
	DROP TABLE snow_white_boss_visit
	DROP TABLE the_cannon_apogee_star
	DROP TABLE the_payne_apogee_star
	DROP TABLE the_payne_apogee_visit
