USE [master]
GO

/****** Object:  Database [BESTTEST_DR14]    Script Date: 3/22/2017 3:19:10 PM ******/
CREATE DATABASE [BESTTEST_DR14]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BESTTEST_DR14', FILENAME = N'D:\data1\sql_db\BESTTEST_DR14\PRIMARY.MDF' , SIZE = 66560KB , MAXSIZE = UNLIMITED, FILEGROWTH = 100MB)
 LOG ON 
( NAME = N'BESTDR8_Log1', FILENAME = N'D:\data1\sql_db\BESTTEST_DR14\Log1.LDF' , SIZE = 655304KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)


ALTER DATABASE [BESTTEST_DR14] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BESTTEST_DR14].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BESTTEST_DR14] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET ANSI_NULLS ON 
GO

ALTER DATABASE [BESTTEST_DR14] SET ANSI_PADDING ON 
GO

ALTER DATABASE [BESTTEST_DR14] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [BESTTEST_DR14] SET ARITHABORT ON 
GO

ALTER DATABASE [BESTTEST_DR14] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BESTTEST_DR14] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BESTTEST_DR14] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [BESTTEST_DR14] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [BESTTEST_DR14] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BESTTEST_DR14] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BESTTEST_DR14] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BESTTEST_DR14] SET  MULTI_USER 
GO

ALTER DATABASE [BESTTEST_DR14] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BESTTEST_DR14] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BESTTEST_DR14] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BESTTEST_DR14] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BESTTEST_DR14] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BESTTEST_DR14] SET  READ_WRITE 
GO


