-----------------------------
--  Inventory.sql
-----------------------------
SET NOCOUNT ON
GO
TRUNCATE TABLE Inventory
GO
--

INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_allstar_dr17_synspec_rev1','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_allwise','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_assignment','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_best_brightest','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_bhm_csc','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_bhm_csc_v2','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_bhm_efeds_veto','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_bhm_rm_tweaks','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_bhm_rm_v0','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_bhm_rm_v0_2','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_bhm_spiders_agn_superset','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_bhm_spiders_clusters_superset','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_cadence','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_cadence_epoch','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_carton','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_carton_csv','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_carton_to_target','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_cataclysmic_variables','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_allstar_dr17_synspec_rev1','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_allwise','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_bhm_csc','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_bhm_efeds_veto','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_bhm_rm_v0','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_bhm_rm_v0_2','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_catwise2020','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_gaia_dr2_source','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_glimpse','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_guvcat','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_legacy_survey_dr8','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_mangatarget','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_marvels_dr11_star','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_marvels_dr12_star','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_mastar_goodstars','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_panstarrs1','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_sdss_dr13_photoobj_primary','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_sdss_dr16_specobj','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_sdss_dr17_specobj','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_skies_v1','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_skies_v2','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_skymapper_dr2','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_supercosmos','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_tic_v8','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_twomass_psc','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_tycho2','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_unwise','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_uvotssc1','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalog_to_xmm_om_suss_4_1','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catalogdb_version','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_category','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_catwise2020','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_design','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_design_mode','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_design_mode_check_results','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_design_to_field','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_ebosstarget_v5','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_erosita_superset_agn','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_erosita_superset_clusters','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_erosita_superset_compactobjects','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_erosita_superset_stars','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_field','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_gaia_assas_sn_cepheids','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_gaia_dr2_ruwe','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_gaia_dr2_source','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_gaia_dr2_wd','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_gaia_unwise_agn','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_gaiadr2_tmass_best_neighbour','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_geometric_distances_gaia_dr2','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_glimpse','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_guvcat','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_hole','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_instrument','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_legacy_catalog_catalogid','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_legacy_survey_dr8','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_magnitude','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_mangadapall','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_mangadrpall','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_mangatarget','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_mapper','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_marvels_dr11_star','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_marvels_dr12_star','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_mastar_goodstars','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_mastar_goodvisits','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_mipsgal','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_mwm_tess_ob','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_observatory','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_obsmode','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_opsdb_apo_camera','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_opsdb_apo_camera_frame','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_opsdb_apo_completion_status','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_opsdb_apo_configuration','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_opsdb_apo_design_to_status','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_opsdb_apo_exposure','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_opsdb_apo_exposure_flavor','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_panstarrs1','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_positioner_status','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_revised_magnitude','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sagitta','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdss_apogeeallstarmerge_r13','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdss_dr13_photoobj_primary','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdss_dr16_qso','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdss_dr16_specobj','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdss_dr17_specobj','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdss_id_flat','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdss_id_stacked','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdss_id_to_catalog','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdss_id_to_catalog_full','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdssv_boss_conflist','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdssv_boss_spall','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdssv_plateholes','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_sdssv_plateholes_meta','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_skies_v1','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_skies_v2','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_skymapper_dr2','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_skymapper_gaia','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_supercosmos','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_target','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_target_union_legacy','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_targetdb_version','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_targeting_generation','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_targeting_generation_to_carton','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_targeting_generation_to_version','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_tess_toi','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_tess_toi_v05','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_tic_v8','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_twomass_psc','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_tycho2','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_unwise','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_uvotssc1','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_xmm_om_suss_4_1','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_yso_clustering','U');
INSERT Inventory VALUES('create_minidb_descriptions_ms','dbo.dr19_zari18pms','U');
GO

------------------------------------
PRINT '132 lines inserted into Inventory'
------------------------------------
GO
